<img src="https://raw.githubusercontent.com/carubbi/MQ/b58af070c45fb17b77640c06c0016859ad366b4d/notebooks/assets/imgs/UNIFOR_logo.png" width="400">
<br>
<b>
<font size="6" face="arial" color="blue">
    Graduação em Ciência da Computação
</font>
</b>
<br>
<b>
<font size="4" face="arial">
    Disciplina: Métodos Quantitativos em Computação
</font>
</b>

**Orientador: Prof. Me. Ricardo Carubbi** <br>
*Docente da Graduação e Pós-Graduação em Ciência de Dados e Inteligência Artificial*<br>
*Laboratório de Ciência de Dados e Inteligência Artificial*<br>
*Universidade de Fortaleza*<br>

# **Aula 11 — Fundamentos, eventos e regras de probabilidade**

## 1. Objetivos de aprendizagem

Ao final da aula, o aluno será capaz de:

- representar o espaço amostral e os eventos de um experimento discreto simples.
- calcular probabilidades por complemento e soma, considerando a sobreposição dos eventos.
- calcular probabilidades condicionais e conjuntas, justificando o denominador e a regra do produto.
- verificar independência e distingui-la de exclusão mútua.

## 2. Agenda

1. Experimento, espaço amostral e eventos — 25 min
2. Complemento, união e interseção — 20 min
3. Regra da soma e exclusão mútua — 25 min
4. Probabilidade condicional e regra do produto — 20 min
5. Independência — 10 min

**Código pronto:** carregamento e conferência das categorias do CSV, funções `validar_evento`, `prob` e `prob_cond`, e configuração da simulação. Desenvolva os cálculos e suas interpretações com a turma.

## 3. Experimento, espaço amostral e eventos

> **Como calcular a probabilidade de um evento?**

### 3.1 Experimento aleatório

Um **experimento aleatório** é um procedimento cujo resultado particular é incerto antes de sua realização. Para descrevê-lo, indicamos o procedimento e o que será registrado como resultado. Ao lançar uma moeda, por exemplo, registramos a face voltada para cima (Barbetta; Reis; Bornia, 2010, pp. 92, 96).

### 3.2 Espaço amostral

O **espaço amostral** $\Omega$ reúne todos os resultados possíveis do experimento. No lançamento da moeda, $\Omega_{\text{moeda}}=\{\text{cara},\text{coroa}\}$. Se lançamos um dado e registramos a face voltada para cima, $\Omega_{\text{dado}}=\{1,2,3,4,5,6\}$. Especificar o que registramos determina quais resultados entram no espaço amostral (Barbetta; Reis; Bornia, 2010, p. 93).

### 3.3 Eventos

Um **evento** é um subconjunto do espaço amostral. Ele ocorre quando o resultado observado pertence a esse subconjunto. Na moeda, o evento “sair cara” é $C=\{\text{cara}\}$. No dado, “sair número par” é $D=\{2,4,6\}$. Se a face observada for 4, ocorreu $D$. Esses conjuntos descrevem possibilidades. Atribuir a mesma probabilidade às faces do dado exige que ele seja honesto e o lançamento, imparcial (Barbetta; Reis; Bornia, 2010, pp. 92, 94, 96).

### 3.4 Axiomas e cálculo da probabilidade

**Probabilidade** é uma função $\mathbb{P}$ que atribui a cada evento $E$ do espaço amostral $\Omega$ um número $\mathbb{P}(E)$ entre 0 e 1 (Montgomery; Runger, 2018, seção 2.3, p. 47). Na moeda honesta com lançamento imparcial, as duas faces têm a mesma probabilidade e $\mathbb{P}(C)=1/2$. Essa igualdade depende da hipótese de equiprobabilidade (Barbetta; Reis; Bornia, 2010, pp. 96–97).

Quando todos os resultados possíveis têm a mesma probabilidade, calculamos a probabilidade pela razão entre resultados favoráveis e resultados possíveis (Barbetta; Reis; Bornia, 2010, pp. 96–97):

$$\mathbb{P}(E)=\frac{n(E)}{n(\Omega)}.
\tag{11.1}
$$

- $n(E)$: número de resultados que pertencem ao evento $E$.
- $n(\Omega)$: número total de resultados possíveis.

No espaço amostral finito desta aula, uma atribuição de probabilidades $\mathbb{P}$ deve satisfazer três axiomas para quaisquer eventos $E$ e $F$ (Montgomery; Runger, 2018, seção 2.3, p. 47):

1. **Não negatividade:** $\mathbb{P}(E)\geq 0$.
2. **Normalização:** $\mathbb{P}(\Omega)=1$.
3. **Aditividade para eventos disjuntos:** se $E\cap F=\varnothing$, então $\mathbb{P}(E\cup F)=\mathbb{P}(E)+\mathbb{P}(F)$.

Em um espaço amostral finito, calculamos a probabilidade de um evento somando as probabilidades de seus resultados elementares (Morettin; Bussab, 2010, p. 122):

$$\mathbb{P}(E)=\sum_{\omega\in E}\mathbb{P}(\{\omega\}).
\tag{11.2}
$$

- $\mathbb{P}(E)$: probabilidade do evento $E$.
- $\omega$: um resultado possível do espaço amostral finito.
- $\mathbb{P}(\{\omega\})$: probabilidade desse resultado.

Considere o exercício 19 de Barbetta, Reis e Bornia. O experimento é selecionar ao acaso um CD entre os 1.000 do lote e registrar sua resistência a arranhão e a situação das trilhas. A tabela apresenta contagens agregadas, não registros individuais (Barbetta; Reis; Bornia, 2010, exercício 19, p. 115).

| Resistência a arranhão | Trilhas aprovadas | Trilhas reprovadas | Total |
| --- | ---: | ---: | ---: |
| Alta | 700 | 140 | 840 |
| Baixa | 100 | 60 | 160 |
| Total | 800 | 200 | 1.000 |

Fonte: Barbetta, Reis e Bornia (2010, exercício 19, p. 115).

O [CSV sintético publicado no GitHub](https://github.com/carubbi/MQ/blob/80cfcb0b3e8cc4d23fcaddf2d1c29ac85ab5483b/notebooks/assets/data/u1_a11_cds.csv) contém 1.000 linhas artificiais que reproduzem essas contagens, embaralhadas com semente 2026. Carregue o CSV e reconstrua a tabela. As linhas não são registros individuais publicados no livro.

**Aplicação com o CSV:** defina $A$ como resistência alta e $B$ como trilhas aprovadas. Calcule as probabilidades das quatro categorias a partir de suas contagens. Depois, identifique os resultados que pertencem a cada evento.

In [1]:
# Carregar o CSV sintético publicado no GitHub
import pandas as pd

url_csv = "https://raw.githubusercontent.com/carubbi/MQ/80cfcb0b3e8cc4d23fcaddf2d1c29ac85ab5483b/notebooks/assets/data/u1_a11_cds.csv"
df = pd.read_csv(url_csv)
df.head()

  resistencia    trilhas
0        Alta  Aprovadas
1        Alta  Aprovadas
2        Alta  Aprovadas
3        Alta  Aprovadas
4        Alta  Aprovadas

In [2]:
# Contar os CDs por resistência e situação das trilhas
tab = pd.crosstab(df["resistencia"], df["trilhas"])
tab

trilhas      Aprovadas  Reprovadas
resistencia
Alta               700         140
Baixa              100          60

In [3]:
# Calcular a probabilidade de cada categoria
tab_prob = tab / len(df)
tab_prob

trilhas      Aprovadas  Reprovadas
resistencia
Alta               0.7        0.14
Baixa              0.1        0.06

In [4]:
# Conferir o tamanho da amostra e os axiomas
n = len(df)
somas = tab_prob.sum()
minimos = tab_prob.min()
axiomas = pd.Series({
    "Total de CDs": n,
    "P(um CD específico)": 1 / n,
    "Probabilidades não negativas": minimos.min() >= 0,
    "Soma das probabilidades": somas.sum(),
})
axiomas

Total de CDs                     1000
P(um CD específico)             0.001
Probabilidades não negativas     True
Soma das probabilidades           1.0
dtype: object

Antes de construir os eventos, confira as colunas originais: valores ausentes ou categorias inesperadas não devem ser classificados como `False`. Cada linha representa um CD; os eventos A e B devem manter os mesmos registros, índices e ordem.

In [5]:
# Conferir as categorias antes de construir os eventos
if not df["resistencia"].isin(["Alta", "Baixa"]).all():
    raise ValueError("Verifique ausências e categorias na resistência.")
if not df["trilhas"].isin(["Aprovadas", "Reprovadas"]).all():
    raise ValueError("Verifique ausências e categorias nas trilhas.")

In [6]:
# Identificar os eventos A e B nos dados
df["A"] = df["resistencia"] == "Alta"
df["B"] = df["trilhas"] == "Aprovadas"
df.head()

  resistencia    trilhas     A     B
0        Alta  Aprovadas  True  True
1        Alta  Aprovadas  True  True
2        Alta  Aprovadas  True  True
3        Alta  Aprovadas  True  True
4        Alta  Aprovadas  True  True

In [7]:
# Calcular a probabilidade de resistência alta
n_a = df["A"].sum()
p_a = n_a / n
print(f"P(A)={p_a:.2f}")

P(A)=0.84

A função `prob` reúne a contagem de `True` e a divisão pelo total. No sorteio uniforme entre os 1.000 CDs, ela calcula a probabilidade no lote. Em uma amostra simulada, calcula a frequência relativa. Ela não atribui pesos diferentes às linhas: aplicá-la às quatro categorias como se fossem equiprováveis seria incorreto. Um evento sempre falso tem probabilidade zero; uma série vazia não fornece um denominador válido.

In [8]:
# Validar a representação booleana de um evento
def validar_evento(A):
    """Verifica a representação de um evento por uma série booleana."""
    if not isinstance(A, pd.Series):
        raise TypeError("O evento deve ser uma série do pandas.")
    if not pd.api.types.is_bool_dtype(A.dtype):
        raise TypeError("A série deve conter valores booleanos.")
    if A.isna().any():
        raise ValueError("Trate os valores ausentes antes do cálculo.")

# Calcular a proporção de registros que pertencem ao evento
def prob(A):
    """Calcula a proporção de True, atribuindo peso igual às linhas."""
    validar_evento(A)
    if A.empty:
        raise ValueError("O conjunto de referência está vazio.")
    return A.sum() / A.size

In [9]:
# Conferir a probabilidade pela função
print(f"P(A)={prob(df['A']):.2f}")

P(A)=0.84

As categorias (Alta, Aprovadas) e (Alta, Reprovadas) pertencem a $A$. As categorias (Alta, Aprovadas) e (Baixa, Aprovadas) pertencem a $B$. Apenas (Alta, Aprovadas) pertence a $A\cap B$. Nenhum dos dois eventos contém o outro. Dividir o número de categorias favoráveis por quatro seria incorreto, pois as categorias não têm probabilidades iguais.

## 4. Complemento, união e interseção

### 4.1 Complemento

O **complemento** $A^{c}$ contém os resultados de $\Omega$ que não estão em $A$ (Barbetta; Reis; Bornia, 2010, pp. 94–96).

$$\mathbb{P}(A^{c})=1-\mathbb{P}(A).
\tag{11.3}
$$

- $A^{c}$: evento em que $A$ não ocorre.
- $1$: probabilidade do evento certo $\Omega$.

O evento impossível $\varnothing$ tem probabilidade zero.

### 4.2 União e interseção

A **união** $A\cup B$ contém os resultados que estão em pelo menos um dos eventos. A **interseção** $A\cap B$ contém apenas os que estão em ambos. “Ou” é inclusivo: um resultado na interseção também pertence à união (Barbetta; Reis; Bornia, 2010, pp. 94–102; Escovedo; Marques; Kalinowski, 2025, pp. 82–86; Morettin; Bussab, 2010, pp. 123–125).

Para os eventos abstratos $A$ e $B$, represente “$A$ sem $B$”, “exatamente um” e “nenhum” (Morettin; Bussab, 2010, problema 8, p. 127). Escreva primeiro as operações entre conjuntos. Depois, confira a pertença das quatro categorias de CDs.

In [10]:
# Organizar a pertença dos CDs aos eventos
df["A_complementar"] = ~df["A"]
df["A_ou_B"] = df["A"] | df["B"]
df["A_e_B"] = df["A"] & df["B"]
df.head()

  resistencia    trilhas     A     B  A_complementar  A_ou_B  A_e_B
0        Alta  Aprovadas  True  True           False    True   True
1        Alta  Aprovadas  True  True           False    True   True
2        Alta  Aprovadas  True  True           False    True   True
3        Alta  Aprovadas  True  True           False    True   True
4        Alta  Aprovadas  True  True           False    True   True

In [11]:
# Calcular as probabilidades dos eventos representados
pd.Series({
    "P(A complementar)": prob(~df["A"]),
    "P(A∪B)": prob(df["A"] | df["B"]),
    "P(A∩B)": prob(df["A"] & df["B"]),
}, name="probabilidade")

P(A complementar)    0.16
P(A∪B)               0.94
P(A∩B)               0.70
Name: probabilidade, dtype: float64

“$A$ sem $B$” é $A\cap B^{c}$ e contém (Alta, Reprovadas), ou 140 CDs. “Exatamente um” é $(A\cap B^{c})\cup(A^{c}\cap B)$ e contém 140 + 100 = 240 CDs. “Nenhum” é $A^{c}\cap B^{c}$ e contém (Baixa, Reprovadas), ou 60 CDs. A classificação dos resultados vem antes do cálculo das probabilidades.

Considere a simulação a seguir faz 100 sorteios com reposição a partir do arquivo de 1.000 CDs. Compare as frequências relativas simuladas com as probabilidades da tabela original.

In [12]:
# Simular novos sorteios a partir dos CDs do arquivo
rep = 100
amostra = df.sample(n=rep, replace=True, random_state=2026, ignore_index=True)
tab_sim = pd.crosstab(amostra["resistencia"], amostra["trilhas"])
tab_sim

trilhas      Aprovadas  Reprovadas
resistencia
Alta                73          15
Baixa                8           4

In [13]:
# Calcular as frequências das quatro categorias com prob
freq_sim = pd.DataFrame({
    "Aprovadas": [
        prob(amostra["A"] & amostra["B"]),
        prob(~amostra["A"] & amostra["B"]),
    ],
    "Reprovadas": [
        prob(amostra["A"] & ~amostra["B"]),
        prob(~amostra["A"] & ~amostra["B"]),
    ],
}, index=["Alta", "Baixa"])
freq_sim.index.name = "resistencia"
freq_sim.columns.name = "trilhas"
freq_sim

trilhas      Aprovadas  Reprovadas
resistencia
Alta              0.73        0.15
Baixa             0.08        0.04

In [14]:
# Comparar frequência simulada e probabilidade no lote
pd.Series({
    "Frequência de A na simulação": prob(amostra["A"]),
    "Probabilidade de A no lote": prob(df["A"]),
})

Frequência de A na simulação    0.88
Probabilidade de A no lote      0.84
dtype: float64

A amostra acima foi **gerada artificialmente** com semente 2026 e 100 sorteios com reposição. Compare a frequência relativa simulada com a probabilidade de cada categoria. Não se espera igualdade exata nem aproximação monotônica a cada repetição. A simulação não recupera novos registros reais do lote.

## 5. Regra da soma e exclusão mútua

### 5.1 Regra geral da soma

Ao somar $\mathbb{P}(A)$ e $\mathbb{P}(B)$, os resultados de $A\cap B$ são contados duas vezes. A **regra geral da soma** corrige essa sobreposição (Barbetta; Reis; Bornia, 2010, pp. 97–102; Morettin; Bussab, 2010, pp. 123–125):

$$\mathbb{P}(A\cup B)=\mathbb{P}(A)+\mathbb{P}(B)-\mathbb{P}(A\cap B).
\tag{11.4}
$$

- $\mathbb{P}(A\cup B)$: probabilidade de ao menos um dos eventos.
- $\mathbb{P}(A\cap B)$: probabilidade da ocorrência simultânea.

Na tabela dos CDs, $A$ indica resistência alta e $B$ indica trilhas aprovadas. Calcule $\mathbb{P}(A)$, $\mathbb{P}(B)$, $\mathbb{P}(A\cap B)$ e $\mathbb{P}(A\cup B)$ usando as contagens originais.

In [15]:
# Calcular a união e conferir a dupla contagem
p_a = prob(df["A"])
p_b = prob(df["B"])
p_ab = prob(df["A"] & df["B"])
p_uniao = p_a + p_b - p_ab
res_soma = pd.Series({
    "P(A)": p_a,
    "P(B)": p_b,
    "P(A∩B)": p_ab,
    "P(A∪B) pela regra": p_uniao,
    "P(A∪B) diretamente": prob(df["A"] | df["B"]),
}, name="probabilidade")
res_soma

P(A)                  0.84
P(B)                  0.80
P(A∩B)                0.70
P(A∪B) pela regra     0.94
P(A∪B) diretamente    0.94
Name: probabilidade, dtype: float64

Obtivemos $\mathbb{P}(A)=0{,}84$, $\mathbb{P}(B)=0{,}80$ e $\mathbb{P}(A\cap B)=0{,}70$. Logo, $\mathbb{P}(A\cup B)=0{,}94$, correspondente a 940 CDs do lote. Somar 0,84 e 0,80 sem retirar a interseção produziria 1,64 e contaria duas vezes os 700 CDs de resistência alta e trilhas aprovadas.

### 5.2 Eventos mutuamente exclusivos

Se os eventos são **mutuamente exclusivos**, $A\cap B=\varnothing$. A regra da soma se reduz a (Barbetta; Reis; Bornia, 2010, pp. 97–102):

$$\mathbb{P}(A\cup B)=\mathbb{P}(A)+\mathbb{P}(B).
\tag{11.5}
$$

Compare as categorias “Alta e Aprovadas” e “Baixa e Reprovadas”. Um único CD selecionado pode pertencer às duas categorias?

In [16]:
# Conferir a união de duas categorias mutuamente exclusivas
n_aa = tab.loc["Alta", "Aprovadas"]
n_br = tab.loc["Baixa", "Reprovadas"]
p_disj = (n_aa + n_br) / n
print(f"P(Alta/Aprovadas ou Baixa/Reprovadas)={p_disj:.2f}")

P(Alta/Aprovadas ou Baixa/Reprovadas)=0.76

As duas categorias são disjuntas para um único CD. A probabilidade da união é 700/1000 + 60/1000 = **0,76**. Já os eventos “resistência alta” e “trilhas aprovadas” se sobrepõem e exigem subtrair a interseção na regra geral da soma.

## 6. Probabilidade condicional e regra do produto

Até aqui, calculamos as probabilidades em relação aos 1.000 CDs do lote. Agora veremos como a informação de que um evento ocorreu muda o conjunto de referência. Depois, usaremos uma probabilidade condicional para calcular a ocorrência conjunta.

### 6.1 Condicionamento

Ao saber que $B$ ocorreu, restringimos a referência aos resultados de $B$. A probabilidade de $A$ **dado** $B$ é a razão entre a probabilidade da interseção e a de $B$ (Barbetta; Reis; Bornia, 2010, pp. 103–105; Morettin; Bussab, 2010, p. 128):

$$\mathbb{P}(A\mid B)=\frac{\mathbb{P}(A\cap B)}{\mathbb{P}(B)},\qquad \mathbb{P}(B)>0.
\tag{11.6}
$$

- $\mathbb{P}(A\mid B)$: probabilidade de resistência alta entre os CDs com trilhas aprovadas.
- $\mathbb{P}(B)$: probabilidade do evento condicionante, que precisa ser positiva.

Use a tabela original para calcular $\mathbb{P}(A\mid B)$ e $\mathbb{P}(B\mid A)$. A primeira razão considera 800 CDs com trilhas aprovadas. A segunda considera 840 CDs com resistência alta. As contagens agregadas são suficientes para as duas razões, desde que cada CD do lote tenha a mesma probabilidade de ser escolhido.

In [17]:
# Comparar os dois sentidos do condicionamento
p_a_dado_b = p_ab / p_b
p_b_dado_a = p_ab / p_a
cond = pd.Series({
    "P(A|B)": p_a_dado_b,
    "P(B|A)": p_b_dado_a,
}, name="probabilidade")
cond

P(A|B)    0.875000
P(B|A)    0.833333
Name: probabilidade, dtype: float64

Entre os 800 CDs com trilhas aprovadas, 700 têm resistência alta. Assim, $\mathbb{P}(A\mid B)=700/800=0{,}875$. Entre os 840 CDs com resistência alta, 700 têm trilhas aprovadas. Assim, $\mathbb{P}(B\mid A)=700/840\approx0{,}8333$. As condicionais inversas diferem porque os conjuntos de referência têm tamanhos diferentes.

Em `prob_cond(A, B)`, a expressão `A[B]` seleciona os valores de A somente nos registros que satisfazem B. A função `prob` passa a dividir pelo tamanho desse subconjunto. As duas séries devem representar os mesmos indivíduos. Se nenhum registro satisfizer B, a condicional não pode ser calculada nesse conjunto.

In [18]:
# Restringir o conjunto de referência ao evento condicionante
def prob_cond(A, B):
    """Calcula a proporção de A entre os registros que satisfazem B."""
    validar_evento(A)
    validar_evento(B)
    if not A.index.equals(B.index):
        raise ValueError("A e B devem ter os mesmos índices e ordem.")
    if not B.any():
        raise ValueError("Não há registros que satisfaçam B.")
    return prob(A[B])

In [19]:
# Conferir os dois sentidos do condicionamento pela seleção dos registros
pd.Series({
    "P(A|B) pela função": prob_cond(df["A"], df["B"]),
    "P(B|A) pela função": prob_cond(df["B"], df["A"]),
}, name="probabilidade")

P(A|B) pela função    0.875000
P(B|A) pela função    0.833333
Name: probabilidade, dtype: float64

### 6.2 Regra geral do produto

Partimos da Equação (11.6), válida quando $\mathbb{P}(B)>0$:

$$
\mathbb{P}(A\mid B)=\frac{\mathbb{P}(A\cap B)}{\mathbb{P}(B)}.
$$

Multiplicamos os dois lados por $\mathbb{P}(B)$:

$$
\mathbb{P}(B)\mathbb{P}(A\mid B)=\mathbb{P}(A\cap B).
$$

Invertendo os lados da igualdade, chegamos à **regra geral do produto** (Barbetta; Reis; Bornia, 2010, pp. 106–109; Morettin; Bussab, 2010, pp. 128–130):

$$\mathbb{P}(A\cap B)=\mathbb{P}(B)\mathbb{P}(A\mid B).
\tag{11.7}
$$

A regra não pressupõe independência.

In [20]:
# Conferir a regra do produto no lote de 1.000 CDs
pd.Series({
    "P(B)P(A|B)": prob(df["B"]) * prob_cond(df["A"], df["B"]),
    "P(A∩B)": prob(df["A"] & df["B"]),
}, name="probabilidade")

P(B)P(A|B)    0.7
P(A∩B)        0.7
Name: probabilidade, dtype: float64

Uma caixa contém 4 CDs de baixa resistência e 8 de alta resistência. Retiramos ao acaso dois CDs, um após o outro, sem reposição, e registramos suas resistências. Esta caixa hipotética troca apenas as cores dos cartões do Exemplo 4.9 por categorias de resistência. Ela não representa o CSV de 1.000 CDs usado nas seções anteriores (Barbetta; Reis; Bornia, 2010, pp. 105–107).

- $L_i$: resistência baixa na retirada $i$.
- $H_i$: resistência alta na retirada $i$.

**a)** Qual é a probabilidade de os dois CDs terem baixa resistência? Aplique $\mathbb{P}(L_1\cap L_2)=\mathbb{P}(L_1)\mathbb{P}(L_2\mid L_1)$.

In [21]:
# Registrar as quantidades da caixa hipotética
n_l = 4
n_h = 8
n_c = n_l + n_h
print(f"Baixa: {n_l} | Alta: {n_h} | Total: {n_c}")

Baixa: 4 | Alta: 8 | Total: 12

In [22]:
# Aplicar a regra do produto a duas resistências baixas
p_ll = (n_l / n_c) * ((n_l - 1) / (n_c - 1))
print(f"P(L₁∩L₂) = {p_ll:.6f}")

P(L₁∩L₂) = 0.090909

O segundo fator considera os CDs restantes após a primeira retirada. Se o primeiro tinha baixa resistência, restam 3 CDs dessa categoria entre 11 CDs.

**b)** Como atribuir probabilidades aos quatro pares ordenados de **categorias observadas**: $(L_1,L_2)$, $(L_1,H_2)$, $(H_1,L_2)$ e $(H_1,H_2)$? Confira se a soma é 1.

In [23]:
# Calcular as probabilidades dos quatro pares ordenados
p_lh = (n_l / n_c) * (n_h / (n_c - 1))
p_hl = (n_h / n_c) * (n_l / (n_c - 1))
p_hh = (n_h / n_c) * ((n_h - 1) / (n_c - 1))
seq = pd.Series({"Baixa, baixa": p_ll, "Baixa, alta": p_lh, "Alta, baixa": p_hl, "Alta, alta": p_hh}, name="probabilidade")
seq

Baixa, baixa    0.090909
Baixa, alta     0.242424
Alta, baixa     0.242424
Alta, alta      0.424242
Name: probabilidade, dtype: float64

In [24]:
# Conferir a soma dos quatro pares ordenados
print(f"Soma = {seq.sum():.6f}")

Soma = 1.000000

**c)** Qual é a probabilidade de ocorrer exatamente um CD de baixa resistência nas duas retiradas?

In [25]:
# Somar os dois pares com exatamente uma resistência baixa
p_um_l = p_lh + p_hl
print(f"P(exatamente uma baixa) = {p_um_l:.6f}")

P(exatamente uma baixa) = 0.484848

**d)** Se retirarmos três CDs sem reposição, qual é a probabilidade de os dois primeiros terem alta resistência e o terceiro ter baixa resistência?

In [26]:
# Aplicar o produto a três retiradas sem reposição
p_hhl = (n_h / n_c) * ((n_h - 1) / (n_c - 1)) * (n_l / (n_c - 2))
print(f"P(alta, alta, baixa) = {p_hhl:.6f}")

P(alta, alta, baixa) = 0.169697

Os quatro pares ordenados esgotam as **categorias observadas** nas duas retiradas, mas não têm probabilidades iguais. Exatamente uma resistência baixa ocorre nos pares $(L_1,H_2)$ e $(H_1,L_2)$. No item d, após duas resistências altas, restam 4 CDs de baixa resistência entre 10 CDs.

## 7. Independência

### 7.1 Verificação da independência

Dois eventos são **independentes** quando saber que um ocorreu não altera a probabilidade do outro. Para dois eventos, podemos verificar a seguinte condição (Barbetta; Reis; Bornia, 2010, pp. 109–110; Morettin; Bussab, 2010, pp. 129–131):

$$\mathbb{P}(A\cap B)=\mathbb{P}(A)\mathbb{P}(B).
\tag{11.8}
$$

Esta fatoração é uma condição a verificar, não um atalho automático. Eventos mutuamente exclusivos de probabilidades positivas não são independentes: a ocorrência de um impede a do outro.

Na tabela a seguir, os números **já são probabilidades** (Morettin; Bussab, 2010, problema 21, p. 132):

| | $B$ | $B^{c}$ | Total |
| --- | ---: | ---: | ---: |
| $A$ | 0,04 | 0,06 | 0,10 |
| $A^{c}$ | 0,08 | 0,82 | 0,90 |
| Total | 0,12 | 0,88 | 1,00 |

Verifique a independência de $A$ e $B$ comparando a célula conjunta com o produto das marginais.

In [27]:
# Mostrar a tabela de probabilidades de Morettin e Bussab
tab_m = pd.DataFrame(
    [[0.04, 0.06], [0.08, 0.82]],
    index=["A", "A complementar"],
    columns=["B", "B complementar"],
)
tab_m

                   B  B complementar
A               0.04            0.06
A complementar  0.08            0.82

In [28]:
# Comparar a conjunta com o produto das marginais
p_a_m = tab_m.loc["A"].sum()
p_b_m = tab_m["B"].sum()
p_ab_m = tab_m.loc["A", "B"]
print(f"P(A∩B)={p_ab_m:.3f} | P(A)P(B)={p_a_m * p_b_m:.3f}")

P(A∩B)=0.040 | P(A)P(B)=0.012

A célula conjunta vale 0,04. O produto das marginais é $0{,}10\times0{,}12=0{,}012$. Como não são iguais, **$A$ e $B$ não são independentes**. A comparação usa probabilidades fornecidas na tabela, não frequências a serem estimadas.

## 8. Estudo e exercícios

### 8.1 Materiais didáticos

- Barbetta, Reis e Bornia (2010), seções 4.1–4.3, pp. 94–110: eventos, soma, condicionamento e independência de dois eventos. É a leitura principal.
- Barbetta, Reis e Bornia (2010), Exemplo 4.9, pp. 105–107: retiradas sem reposição e regra do produto. A caixa de 12 CDs troca somente as categorias dos cartões originais.
- Morettin e Bussab (2010), Exemplo 5.13, p. 131: dois componentes em série e paralelo, com independência declarada.
- PINHEIRO et al. (2009), Exemplo 3.8, pp. 97–100: leitura complementar para distinguir soma e produto.

### 8.2 Exercícios indicados

- Morettin e Bussab (2010), problema 8, p. 127: representar “A sem B”, “exatamente um” e “nenhum”.
- PINHEIRO et al. (2009), exercício 3.2_P, p. 109: tentativas entre seis ordens sem repetir. Justifique o produto condicional.
- Morettin e Bussab (2010), problema 18, p. 132: condicionamento no dado viciado.
- Morettin e Bussab (2010), problema 21, p. 132: conferir independência na tabela de probabilidades.
- PINHEIRO et al. (2009), exercícios 3.3_P, pp. 109–110, e 3.4_P, p. 110: complemento, união e independência sob as hipóteses dadas.
- NAVIDI (2024), seção 2.3, exercício 21, p. 109: discutir independência e causa comum de falha.

## 9. Referências

1. BARBETTA, Pedro Alberto; REIS, Marcelo Menezes; BORNIA, Antonio Cezar. *Estatística para cursos de engenharia e informática*. 3. ed. São Paulo: Atlas, 2010.
2. PINHEIRO, João Ismael D. et al. *Estatística básica: a arte de trabalhar com dados*. Rio de Janeiro: Elsevier, 2009.
3. MORETTIN, Pedro A.; BUSSAB, Wilton O. *Estatística básica*. 6. ed. São Paulo: Saraiva, 2010.
4. ESCOVEDO, Tatiana; MARQUES, Thiago; KALINOWSKI, Marcos. *Introdução à estatística para ciência de dados*. São Paulo: Casa do Código, 2025.
5. MONTGOMERY, Douglas C.; RUNGER, George C. *Applied Statistics and Probability for Engineers*. 7. ed. Hoboken: Wiley, 2018.
6. NAVIDI, William. *Statistics for Engineers and Scientists*. 6. ed. New York: McGraw Hill, 2024.