<img src="https://raw.githubusercontent.com/carubbi/MQ/b58af070c45fb17b77640c06c0016859ad366b4d/notebooks/assets/imgs/UNIFOR_logo.png" width="400">
<br>
<b>
<font size="6" face="arial" color="blue">
    Graduação em Ciência da Computação
</font>
</b>
<br>
<b>
<font size="4" face="arial">
    Disciplina: Métodos Quantitativos em Computação
</font>
</b>

**Orientador: Prof. Me. Ricardo Carubbi** <br>
*Docente da Graduação e Pós-Graduação em Ciência de Dados e Inteligência Artificial*<br>
*Laboratório de Ciência de Dados e Inteligência Artificial*<br>
*Universidade de Fortaleza*<br>

# **Aula 12 — Probabilidade total, Bayes e acompanhamento final da AP1**

## 1. Objetivos de aprendizagem

Ao final da aula, o aluno será capaz de:

- identificar uma partição discreta e calcular a probabilidade de uma evidência pela regra da probabilidade total.
- atualizar a probabilidade de um grupo após observar uma evidência com o Teorema de Bayes.
- distinguir a probabilidade da evidência em um grupo da probabilidade do grupo dada a evidência.
- explicar como a probabilidade inicial (a priori) altera a probabilidade posterior quando as probabilidades condicionais da evidência permanecem iguais.

## 2. Agenda

1. Partições e probabilidade total — 30 min
2. Teorema de Bayes e probabilidade inicial — 40 min
3. Acompanhamento final da AP1 — 30 min

Os 30 minutos finais são reservados ao acompanhamento da AP1 no repositório da dupla.

## 3. Partições e probabilidade total

> **Como atualizar uma probabilidade após observar uma nova evidência?**

### 3.1 Partição do espaço amostral

Uma **partição** divide o espaço amostral em grupos que não se sobrepõem e que, juntos, cobrem todos os resultados possíveis. Por exemplo, ao lançar um dado, “face par” e “face ímpar” formam uma partição. Cada resultado pertence a exatamente um dos grupos (Barbetta; Reis; Bornia, 2010, pp. 110–111).

$$
G_i\cap G_j=\varnothing\quad(i\ne j),\qquad \bigcup_{i=1}^{k}G_i=\Omega.\tag{12.1}
$$

Aqui, $\Omega$ é o espaço amostral, $G_1,\ldots,G_k$ são os grupos da partição, $\cap$ representa a interseção, $\cup$ representa a união e $\varnothing$ é o conjunto vazio. Para usar uma probabilidade condicionada a $G_i$, exigimos $\mathbb{P}(G_i)>0$.

### 3.2 Regra da probabilidade total

Se a evidência $E$ pode ocorrer em qualquer grupo da partição, podemos separá-la em parcelas disjuntas (Barbetta; Reis; Bornia, 2010, pp. 110–111).

$$
E=\bigcup_{i=1}^{k}(E\cap G_i).\tag{12.2}
$$

Pela regra do produto, a probabilidade de cada parcela é a probabilidade inicial do grupo multiplicada pela probabilidade de $E$ nesse grupo. A soma das parcelas fornece a **probabilidade total** de $E$ (Barbetta; Reis; Bornia, 2010, p. 111).

$$
\mathbb{P}(E)=\sum_{i=1}^{k}\mathbb{P}(G_i)\mathbb{P}(E\mid G_i).\tag{12.3}
$$

Aqui, $\mathbb{P}(G_i)$ é a probabilidade inicial do grupo, $\mathbb{P}(E\mid G_i)$ é a probabilidade da evidência dentro dele e $\mathbb{P}(E)$ é a probabilidade da evidência considerando todos os grupos. Não basta somar as probabilidades condicionais. Cada uma deve receber o peso do seu grupo.

### 3.3 Exercício 1

Entre profissionais de psicologia, 60% atuam na área clínica, 20% na empresarial e 20% em outras áreas. Usam regularmente o computador 10% dos profissionais da área clínica, 70% da empresarial e 40% das outras áreas. Qual é a probabilidade de selecionar uma pessoa que **não** usa regularmente o computador? Os percentuais são os dados do enunciado, não observações individuais (Pinheiro et al., 2009, p. 94).

| Área | Probabilidade inicial | $\mathbb{P}(\text{usa}\mid\text{área})$ | $\mathbb{P}(\text{não usa}\mid\text{área})$ |
| --- | ---: | ---: | ---: |
| Clínica | 0,60 | 0,10 | 0,90 |
| Empresarial | 0,20 | 0,70 | 0,30 |
| Outras | 0,20 | 0,40 | 0,60 |

Antes de executar o código, identifique a partição e estime se o resultado deve ficar acima ou abaixo de 0,50.

**Cálculo manual.** As contribuições para “não usa” são $0{,}60\times0{,}90=0{,}54$ na área clínica, $0{,}20\times0{,}30=0{,}06$ na empresarial e $0{,}20\times0{,}60=0{,}12$ nas outras áreas. A probabilidade total é $0{,}54+0{,}06+0{,}12=0{,}72$.

In [1]:
# Organizar os percentuais fornecidos no exercício
import pandas as pd
from math import isclose

# Montar a tabela do enunciado
df = pd.DataFrame({
    "area": ["Clínica", "Empresarial", "Outras"],
    "p_area": [0.60, 0.20, 0.20],
    "p_usa": [0.10, 0.70, 0.40],
})
df

          area  p_area  p_usa
0      Clínica     0.6    0.1
1  Empresarial     0.2    0.7
2       Outras     0.2    0.4

In [2]:
# Obter a probabilidade de não usar em cada área
df["p_nao_usa"] = 1 - df["p_usa"]
df

          area  p_area  p_usa  p_nao_usa
0      Clínica     0.6    0.1        0.9
1  Empresarial     0.2    0.7        0.3
2       Outras     0.2    0.4        0.6

In [3]:
# Calcular a contribuição conjunta de cada área
df["p_area_e_nao_usa"] = df["p_area"] * df["p_nao_usa"]
df

          area  p_area  p_usa  p_nao_usa  p_area_e_nao_usa
0      Clínica     0.6    0.1        0.9              0.54
1  Empresarial     0.2    0.7        0.3              0.06
2       Outras     0.2    0.4        0.6              0.12

In [4]:
# Somar as contribuições para obter a probabilidade total
p_nao = float(df["p_area_e_nao_usa"].sum())
round(p_nao, 2)

0.72

In [5]:
# Conferir o cálculo manual do item a
isclose(p_nao, 0.72)

True

A conferência em Python reproduz o cálculo manual. O valor $0{,}72$ descreve a probabilidade de **não usar computador** no conjunto das três áreas, segundo as proporções fornecidas no exercício.

## 4. Teorema de Bayes e probabilidade inicial

### 4.1 Atualização da probabilidade

O **Teorema de Bayes** responde a uma pergunta: depois de observar uma evidência, qual é a probabilidade de pertencer a determinado grupo? A probabilidade inicial, também chamada **a priori**, é $\mathbb{P}(G_j)$. Após observar $E$, a probabilidade **posterior** é $\mathbb{P}(G_j\mid E)$. Essas duas probabilidades podem ser diferentes. A probabilidade da evidência no grupo, $\mathbb{P}(E\mid G_j)$, também não é a posterior (Morettin; Bussab, 2010, pp. 116–118).

$$
\mathbb{P}(G_j\mid E)=\frac{\mathbb{P}(G_j)\mathbb{P}(E\mid G_j)}{\sum_{i=1}^{k}\mathbb{P}(G_i)\mathbb{P}(E\mid G_i)},\qquad \mathbb{P}(E)>0.\tag{12.4}
$$

Aqui, $G_j$ é o grupo de interesse, $E$ é a evidência observada, o numerador é a probabilidade conjunta de $G_j$ e $E$, e o denominador é a probabilidade total de $E$. A fórmula resulta da definição de probabilidade condicional, da regra do produto e da Equação (12.3) (Barbetta; Reis; Bornia, 2010, p. 112).

### 4.2 Exercício 2

Entre os profissionais que **não** usam regularmente o computador, qual é a probabilidade de a pessoa atuar na área clínica? Compare essa pergunta com “qual é a probabilidade de não usar computador entre profissionais da área clínica?” (Pinheiro et al., 2009, p. 94).

**Cálculo manual.** A contribuição conjunta da área clínica para o não uso é $0{,}60\times0{,}90=0{,}54$. A probabilidade total de não uso, calculada no item a, é $0{,}72$. Logo, $\mathbb{P}(\text{clínica}\mid\text{não usa})=0{,}54/0{,}72=0{,}75$. Já $\mathbb{P}(\text{não usa}\mid\text{clínica})=0{,}90$. A inversão muda o grupo de referência.

In [6]:
# Calcular a probabilidade da área clínica após observar o não uso
p_clin_nao = float(df.loc[0, "p_area_e_nao_usa"])
prob = p_clin_nao / p_nao
round(prob, 2)

0.75

In [7]:
# Conferir o cálculo manual do item b
isclose(prob, 0.75)

True

O código confirma $0{,}75$. O evento condicionado agora é **não usar computador**, que reúne pessoas das três áreas. Por isso, a probabilidade posterior não é igual a $0{,}90$.

### 4.3 Exercício 3

Um teste de gravidez tem **sensibilidade** de 0,98 e **especificidade** de 0,95. A probabilidade inicial de gravidez no cenário do enunciado é 0,20. Calcule a probabilidade de gravidez após resultado positivo e a probabilidade de não gravidez após resultado negativo (Pinheiro et al., 2009, p. 94).

- $G$: gravidez. $G^c$: não gravidez.
- $+$: resultado positivo. $-$: resultado negativo.
- Sensibilidade: $\mathbb{P}(+\mid G)=0{,}98$.
- Especificidade: $\mathbb{P}(-\mid G^c)=0{,}95$.

As probabilidades complementares são $\mathbb{P}(+\mid G^c)=0{,}05$ e $\mathbb{P}(-\mid G)=0{,}02$. O valor inicial de 0,20 é uma premissa deste exercício, não uma prevalência geral nem uma recomendação clínica.

$$
\mathbb{P}(G\mid +)=\frac{\mathbb{P}(+\mid G)\mathbb{P}(G)}{\mathbb{P}(+\mid G)\mathbb{P}(G)+\mathbb{P}(+\mid G^c)\mathbb{P}(G^c)}.\tag{12.5}
$$

$$
\mathbb{P}(G^c\mid -)=\frac{\mathbb{P}(-\mid G^c)\mathbb{P}(G^c)}{\mathbb{P}(-\mid G)\mathbb{P}(G)+\mathbb{P}(-\mid G^c)\mathbb{P}(G^c)}.\tag{12.6}
$$

Os símbolos $G$, $G^c$, $+$ e $-$ estão definidos acima. Em cada fórmula, o denominador é a probabilidade total do resultado observado.

**Cálculo manual.** Para o resultado positivo, $\mathbb{P}(+)=0{,}98\times0{,}20+0{,}05\times0{,}80=0{,}236$ e $\mathbb{P}(G\mid +)=0{,}196/0{,}236\approx0{,}8305$. Para o negativo, $\mathbb{P}(-)=0{,}02\times0{,}20+0{,}95\times0{,}80=0{,}764$ e $\mathbb{P}(G^c\mid -)=0{,}760/0{,}764\approx0{,}9948$.

In [8]:
# Registrar as probabilidades do enunciado
p_g = 0.20
sens = 0.98
esp = 0.95
pd.Series({"P(G)": p_g, "sensibilidade": sens, "especificidade": esp})

P(G)              0.20
sensibilidade     0.98
especificidade    0.95
dtype: float64

In [9]:
# Calcular a probabilidade total de resultado positivo
p_pos = p_g * sens + (1 - p_g) * (1 - esp)
round(p_pos, 3)

0.236

In [10]:
# Calcular a probabilidade de gravidez dado resultado positivo
p_g_pos = p_g * sens / p_pos
round(p_g_pos, 4)

0.8305

In [11]:
# Calcular a probabilidade total de resultado negativo
p_neg = p_g * (1 - sens) + (1 - p_g) * esp
p_neg

0.764

In [12]:
# Calcular a probabilidade de não gravidez dado resultado negativo
p_nao_g_neg = (1 - p_g) * esp / p_neg
round(p_nao_g_neg, 4)

0.9948

In [13]:
# Conferir as duas probabilidades posteriores manuais
isclose(p_g_pos, 49 / 59) and isclose(p_nao_g_neg, 190 / 191)

True

**Comparação hipotética.** Mantemos sensibilidade e especificidade iguais às do exercício, mas trocamos a probabilidade inicial de 0,20 por 0,01. Essa troca define outro cenário. Ela não muda os dados do enunciado.

In [14]:
# Comparar dois valores da probabilidade inicial
p_alt = 0.01
p_pos_alt = p_alt * sens + (1 - p_alt) * (1 - esp)
p_g_pos_alt = p_alt * sens / p_pos_alt

# Organizar a comparação dos cenários
tab = pd.DataFrame({
    "P(G) inicial": [p_g, p_alt],
    "P(G | positivo)": [p_g_pos, p_g_pos_alt],
})
tab

   P(G) inicial  P(G | positivo)
0          0.20         0.830508
1          0.01         0.165261

Com probabilidade inicial de $0{,}20$, a posterior após resultado positivo é aproximadamente $0{,}8305$. No cenário hipotético com probabilidade inicial de $0{,}01$, ela cai para aproximadamente $0{,}1653$. O mesmo teste produz posteriores diferentes porque a probabilidade inicial mudou. Essa é uma comparação matemática entre cenários, não uma conclusão clínica.

## 5. Estudo e exercícios

Os dois exercícios foram desenvolvidos na aula. Refaça as contas manualmente antes de consultar a versão resolvida e confira cada resultado com o código.

### 5.1 Materiais didáticos

- BARBETTA; REIS; BORNIA (2010), seção 4.4, pp. 110–111 do livro: partição e probabilidade total.
- BARBETTA; REIS; BORNIA (2010), seção 4.5, p. 112 do livro: Teorema de Bayes.
- MORETTIN; BUSSAB (2010), seção 5.4, pp. 116–120 do livro: probabilidade inicial, posterior e atualização.

### 5.2 Exercícios indicados

- PINHEIRO et al. (2009), exercício 3.8_P, p. 94 do livro: calcule a probabilidade de não usar computador nas três áreas e depois a probabilidade da área clínica dado o não uso. Explique por que os denominadores dos itens a e b são diferentes.
- PINHEIRO et al. (2009), exercício 3.9_P, p. 94 do livro: calcule as duas probabilidades posteriores do teste. Indique as probabilidades complementares usadas em cada denominador.

## 6. Referências

1. BARBETTA, Pedro Alberto; REIS, Marcelo Menezes; BORNIA, Antonio Cezar. *Estatística para cursos de engenharia e informática*. 3. ed. São Paulo: Atlas, 2010.
2. MORETTIN, Pedro A.; BUSSAB, Wilton O. *Estatística básica*. 6. ed. São Paulo: Saraiva, 2010.
3. PINHEIRO, João Ismael D. et al. *Estatística básica: a arte de trabalhar com dados*. Rio de Janeiro: Elsevier, 2009.