<img src="https://raw.githubusercontent.com/carubbi/MQ/b58af070c45fb17b77640c06c0016859ad366b4d/notebooks/assets/imgs/UNIFOR_logo.png" width="400">
<br>
<b>
<font size="6" face="arial" color="blue">
    Graduação em Ciência da Computação
</font>
</b>
<br>
<b>
<font size="4" face="arial">
    Disciplina: Métodos Quantitativos em Computação
</font>
</b>

**Orientador: Prof. Me. Ricardo Carubbi** <br>
*Docente da Graduação e Pós-Graduação em Ciência de Dados e Inteligência Artificial*<br>
*Laboratório de Ciência de Dados e Inteligência Artificial*<br>
*Universidade de Fortaleza*<br>

# **Aula 1 — Fundamentos, eventos e atualização de probabilidades**

## 1. Objetivos de aprendizagem

Ao final da aula, o aluno será capaz de:

- representar o espaço amostral e os eventos de um experimento discreto simples.
- calcular probabilidades por complemento e soma, considerando a sobreposição dos eventos.
- calcular probabilidades condicionais e conjuntas, justificando o denominador e a regra do produto.
- identificar uma partição e calcular a probabilidade total de uma evidência.
- atualizar a probabilidade de um grupo pelo Teorema de Bayes e interpretar o efeito da taxa-base.
- verificar independência e distingui-la de exclusão mútua.

**Resultado observável canônico:** Representar eventos, calcular probabilidades simples, conjuntas, condicionais e totais, atualizar probabilidades pelo Teorema de Bayes e distinguir independência de exclusão mútua.

**Identidade editorial:** esta ampliação posterior reúne integralmente os conceitos das Aulas 11 e 12 em um percurso de estudo. Ela não afirma que probabilidade total e Bayes tenham sido ministrados em 11/09/2026.

## 2. Agenda

1. Experimento, espaço amostral e eventos — 15 min
2. Complemento, união e interseção — 15 min
3. Regra da soma e exclusão mútua — 10 min
4. Probabilidade condicional e regra do produto — 20 min
5. Partições e probabilidade total — 15 min
6. Teorema de Bayes e probabilidade inicial — 15 min
7. Independência — 10 min

**Duração institucional da Aula 1:** 100 minutos. Esta agenda registra o percurso editorial integrado; o conteúdo acrescentado após o encontro permanece disponível para estudo, sem reconstituir o que foi ensinado naquela data.

## 3. Experimento, espaço amostral e eventos

> **Como calcular a probabilidade de um evento?**

### 3.1 Experimento aleatório

Um **experimento aleatório** é um procedimento cujo resultado particular é incerto antes de sua realização. Para descrevê-lo, indicamos o procedimento e o que será registrado como resultado. Ao lançar uma moeda, por exemplo, registramos a face voltada para cima (Barbetta; Reis; Bornia, 2010, pp. 92, 96).

### 3.2 Espaço amostral

O **espaço amostral** $\Omega$ reúne todos os resultados possíveis do experimento. No lançamento da moeda, $\Omega_{\text{moeda}}=\{\text{cara},\text{coroa}\}$. Se lançamos um dado e registramos a face voltada para cima, $\Omega_{\text{dado}}=\{1,2,3,4,5,6\}$. Especificar o que registramos determina quais resultados entram no espaço amostral (Barbetta; Reis; Bornia, 2010, p. 93).

### 3.3 Eventos

Um **evento** é um subconjunto do espaço amostral. Ele ocorre quando o resultado observado pertence a esse subconjunto. Na moeda, o evento “sair cara” é $C=\{\text{cara}\}$. No dado, “sair número par” é $D=\{2,4,6\}$. Se a face observada for 4, ocorreu $D$. Esses conjuntos descrevem possibilidades. Atribuir a mesma probabilidade às faces do dado exige que ele seja honesto e o lançamento, imparcial (Barbetta; Reis; Bornia, 2010, pp. 92, 94, 96).

### 3.4 Axiomas e cálculo da probabilidade

**Probabilidade** é uma função $\mathbb{P}$ que atribui a cada evento $E$ do espaço amostral $\Omega$ um número $\mathbb{P}(E)$ entre 0 e 1 (Montgomery; Runger, 2018, seção 2.3, p. 47). Na moeda honesta com lançamento imparcial, as duas faces têm a mesma probabilidade e $\mathbb{P}(C)=1/2$. Essa igualdade depende da hipótese de equiprobabilidade (Barbetta; Reis; Bornia, 2010, pp. 96–97).

Quando todos os resultados possíveis têm a mesma probabilidade, calculamos a probabilidade pela razão entre resultados favoráveis e resultados possíveis (Barbetta; Reis; Bornia, 2010, pp. 96–97):

$$\mathbb{P}(E)=\frac{n(E)}{n(\Omega)}.
\tag{1.1}
$$

- $n(E)$: número de resultados que pertencem ao evento $E$.
- $n(\Omega)$: número total de resultados possíveis.

No espaço amostral finito desta aula, uma atribuição de probabilidades $\mathbb{P}$ deve satisfazer três axiomas para quaisquer eventos $E$ e $F$ (Montgomery; Runger, 2018, seção 2.3, p. 47):

1. **Não negatividade:** $\mathbb{P}(E)\geq 0$.
2. **Normalização:** $\mathbb{P}(\Omega)=1$.
3. **Aditividade para eventos disjuntos:** se $E\cap F=\varnothing$, então $\mathbb{P}(E\cup F)=\mathbb{P}(E)+\mathbb{P}(F)$.

Em um espaço amostral finito, calculamos a probabilidade de um evento somando as probabilidades de seus resultados elementares (Morettin; Bussab, 2010, p. 122):

$$\mathbb{P}(E)=\sum_{\omega\in E}\mathbb{P}(\{\omega\}).
\tag{1.2}
$$

- $\mathbb{P}(E)$: probabilidade do evento $E$.
- $\omega$: um resultado possível do espaço amostral finito.
- $\mathbb{P}(\{\omega\})$: probabilidade desse resultado.

Considere o exercício 19 de Barbetta, Reis e Bornia. O experimento é selecionar ao acaso um CD entre os 1.000 do lote e registrar sua resistência a arranhão e a situação das trilhas. A tabela apresenta contagens agregadas, não registros individuais (Barbetta; Reis; Bornia, 2010, exercício 19, p. 115).

| Resistência a arranhão | Trilhas aprovadas | Trilhas reprovadas | Total |
| --- | ---: | ---: | ---: |
| Alta | 700 | 140 | 840 |
| Baixa | 100 | 60 | 160 |
| Total | 800 | 200 | 1.000 |

Fonte: Barbetta, Reis e Bornia (2010, exercício 19, p. 115).

O [CSV sintético publicado no GitHub](https://github.com/carubbi/MQ/blob/80cfcb0b3e8cc4d23fcaddf2d1c29ac85ab5483b/notebooks/assets/data/u1_a11_cds.csv) contém 1.000 linhas artificiais que reproduzem essas contagens, embaralhadas com semente 2026. Carregue o CSV e reconstrua a tabela. As linhas não são registros individuais publicados no livro.

**Aplicação com o CSV:** defina $A$ como resistência alta e $B$ como trilhas aprovadas. Calcule as probabilidades das quatro categorias a partir de suas contagens. Depois, identifique os resultados que pertencem a cada evento.

In [1]:
# CARREGAR O CSV SINTÉTICO PUBLICADO NO GITHUB
import pandas as pd

url_csv = "https://raw.githubusercontent.com/carubbi/MQ/80cfcb0b3e8cc4d23fcaddf2d1c29ac85ab5483b/notebooks/assets/data/u1_a11_cds.csv"
df = pd.read_csv(url_csv)
df.head()

  resistencia    trilhas
0        Alta  Aprovadas
1        Alta  Aprovadas
2        Alta  Aprovadas
3        Alta  Aprovadas
4        Alta  Aprovadas

In [2]:
# CONTAR OS CDS POR RESISTÊNCIA E SITUAÇÃO DAS TRILHAS
tab = pd.crosstab(df["resistencia"], df["trilhas"])
tab

trilhas      Aprovadas  Reprovadas
resistencia
Alta               700         140
Baixa              100          60

In [3]:
# CALCULAR A PROBABILIDADE DE CADA CATEGORIA
tab_prob = tab / len(df)
tab_prob

trilhas      Aprovadas  Reprovadas
resistencia
Alta               0.7        0.14
Baixa              0.1        0.06

In [4]:
# CONFERIR O TAMANHO DA AMOSTRA E OS AXIOMAS
n = len(df)
somas = tab_prob.sum()
minimos = tab_prob.min()
axiomas = pd.Series({
    "Total de CDs": n,
    "P(um CD específico)": 1 / n,
    "Probabilidades não negativas": minimos.min() >= 0,
    "Soma das probabilidades": somas.sum(),
})
axiomas

Total de CDs                     1000
P(um CD específico)             0.001
Probabilidades não negativas     True
Soma das probabilidades           1.0
dtype: object

Antes de construir os eventos, confira as colunas originais: valores ausentes ou categorias inesperadas não devem ser classificados como `False`. Cada linha representa um CD; os eventos A e B devem manter os mesmos registros, índices e ordem.

In [5]:
# CONFERIR AS CATEGORIAS ANTES DE CONSTRUIR OS EVENTOS
if not df["resistencia"].isin(["Alta", "Baixa"]).all():
    raise ValueError("Verifique ausências e categorias na resistência.")
if not df["trilhas"].isin(["Aprovadas", "Reprovadas"]).all():
    raise ValueError("Verifique ausências e categorias nas trilhas.")

In [6]:
# IDENTIFICAR OS EVENTOS A E B NOS DADOS
df["A"] = df["resistencia"] == "Alta"
df["B"] = df["trilhas"] == "Aprovadas"
df.head()

  resistencia    trilhas     A     B
0        Alta  Aprovadas  True  True
1        Alta  Aprovadas  True  True
2        Alta  Aprovadas  True  True
3        Alta  Aprovadas  True  True
4        Alta  Aprovadas  True  True

In [7]:
# CALCULAR A PROBABILIDADE DE RESISTÊNCIA ALTA
n_a = df["A"].sum()
p_a = n_a / n
print(f"P(A)={p_a:.2f}")

P(A)=0.84

In [8]:
# VALIDAR A REPRESENTAÇÃO BOOLEANA DE UM EVENTO
def validar_evento(A):
    """Verifica a representação de um evento por uma série booleana."""
    if not isinstance(A, pd.Series):
        raise TypeError("O evento deve ser uma série do pandas.")
    if not pd.api.types.is_bool_dtype(A.dtype):
        raise TypeError("A série deve conter valores booleanos.")
    if A.isna().any():
        raise ValueError("Trate os valores ausentes antes do cálculo.")

# CALCULAR A PROPORÇÃO DE REGISTROS QUE PERTENCEM AO EVENTO
def prob(A):
    """Calcula a proporção de True, atribuindo peso igual às linhas."""
    validar_evento(A)
    if A.empty:
        raise ValueError("O conjunto de referência está vazio.")
    return A.sum() / A.size

In [9]:
# CONFERIR A PROBABILIDADE PELA FUNÇÃO
print(f"P(A)={prob(df['A']):.2f}")

P(A)=0.84

In [10]:
# MOSTRAR A PERTENÇA E A PROBABILIDADE DAS QUATRO CATEGORIAS.
categorias = df.groupby(["resistencia", "trilhas"])[["A", "B"]].first()
categorias["A e B"] = categorias["A"] & categorias["B"]
categorias["Contagem"] = df.groupby(["resistencia", "trilhas"]).size()
categorias["Probabilidade"] = categorias["Contagem"] / n
categorias

                            A      B  A e B  Contagem  Probabilidade
resistencia trilhas
Alta        Aprovadas    True   True   True       700           0.70
            Reprovadas   True  False  False       140           0.14
Baixa       Aprovadas   False   True  False       100           0.10
            Reprovadas  False  False  False        60           0.06

As categorias (Alta, Aprovadas) e (Alta, Reprovadas) pertencem a $A$. As categorias (Alta, Aprovadas) e (Baixa, Aprovadas) pertencem a $B$. Apenas (Alta, Aprovadas) pertence a $A\cap B$. Nenhum dos dois eventos contém o outro. Dividir o número de categorias favoráveis por quatro seria incorreto, pois as categorias não têm probabilidades iguais.

No cálculo de $P(A)$, o numerador é a contagem de 840 CDs com resistência alta, e o denominador é o total de 1.000 CDs. As quatro categorias têm probabilidades 0,70, 0,14, 0,10 e 0,06; contar apenas categorias daria pesos incorretos.

## 4. Complemento, união e interseção

### 4.1 Complemento

O **complemento** $A^{c}$ contém os resultados de $\Omega$ que não estão em $A$ (Barbetta; Reis; Bornia, 2010, pp. 94–96).

$$\mathbb{P}(A^{c})=1-\mathbb{P}(A).
\tag{1.3}
$$

- $A^{c}$: evento em que $A$ não ocorre.
- $1$: probabilidade do evento certo $\Omega$.

O evento impossível $\varnothing$ tem probabilidade zero.

### 4.2 União e interseção

A **união** $A\cup B$ contém os resultados que estão em pelo menos um dos eventos. A **interseção** $A\cap B$ contém apenas os que estão em ambos. “Ou” é inclusivo: um resultado na interseção também pertence à união (Barbetta; Reis; Bornia, 2010, pp. 94–102; Escovedo; Marques; Kalinowski, 2025, pp. 82–86; Morettin; Bussab, 2010, pp. 123–125).

![Três diagramas de Venn com as regiões de união, interseção e complemento sombreadas.](https://raw.githubusercontent.com/carubbi/MQ/b58af070c45fb17b77640c06c0016859ad366b4d/notebooks/assets/imgs/u1_a11/barbetta_figura_4_2_operacoes_eventos.png)

**Figura 1 - União, interseção e complemento de eventos.** No painel (a), a região sombreada inclui os resultados de $A$ ou $B$, inclusive os comuns aos dois; no (b), inclui apenas os resultados comuns; no (c), inclui os resultados de $\Omega$ fora de $A$. Fonte: BARBETTA; REIS; BORNIA, 2010, p. 95.

Para os eventos abstratos $A$ e $B$, represente “$A$ sem $B$”, “exatamente um” e “nenhum” (Morettin; Bussab, 2010, problema 8, p. 127). Escreva primeiro as operações entre conjuntos. Depois, confira a pertença das quatro categorias de CDs.

In [11]:
# ORGANIZAR A PERTENÇA DOS CDS AOS EVENTOS
df["A_c"] = ~df["A"]
df["A_ou_B"] = df["A"] | df["B"]
df["A_e_B"] = df["A"] & df["B"]
df.head()

  resistencia    trilhas     A     B    A_c  A_ou_B  A_e_B
0        Alta  Aprovadas  True  True  False    True   True
1        Alta  Aprovadas  True  True  False    True   True
2        Alta  Aprovadas  True  True  False    True   True
3        Alta  Aprovadas  True  True  False    True   True
4        Alta  Aprovadas  True  True  False    True   True

In [12]:
# CALCULAR AS PROBABILIDADES DOS EVENTOS REPRESENTADOS
print("P(A complementar):", prob(df["A_c"]))
print("P(A∪B):", prob(df["A_ou_B"]))
print("P(A∩B):", prob(df["A_e_B"]))

P(A complementar): 0.16
P(A∪B): 0.94
P(A∩B): 0.7

In [13]:
# CALCULAR OS EVENTOS COMPOSTOS PEDIDOS NA ATIVIDADE.
a_sem_b = df["A"] & ~df["B"]
exatamente_um = (df["A"] & ~df["B"]) | (~df["A"] & df["B"])
nenhum = ~df["A"] & ~df["B"]
res_eventos = pd.DataFrame({
    "Contagem": [a_sem_b.sum(), exatamente_um.sum(), nenhum.sum()],
    "Probabilidade": [prob(a_sem_b), prob(exatamente_um), prob(nenhum)],
}, index=["A sem B", "Exatamente um", "Nenhum"])
res_eventos

               Contagem  Probabilidade
A sem B             140           0.14
Exatamente um       240           0.24
Nenhum               60           0.06

“$A$ sem $B$” é $A\cap B^{c}$ e contém (Alta, Reprovadas), ou 140 CDs. “Exatamente um” é $(A\cap B^{c})\cup(A^{c}\cap B)$ e contém 140 + 100 = 240 CDs. “Nenhum” é $A^{c}\cap B^{c}$ e contém (Baixa, Reprovadas), ou 60 CDs. A classificação dos resultados vem antes do cálculo das probabilidades.

No código, `~` representa complemento, `&` representa interseção e `|` representa união inclusiva. Assim, “exatamente um” exclui os 700 CDs que pertencem simultaneamente a $A$ e $B$.

A simulação a seguir faz 100 sorteios com reposição a partir do arquivo de 1.000 CDs. Compare as frequências relativas simuladas com as probabilidades da tabela original.

In [14]:
# SIMULAR NOVOS SORTEIOS A PARTIR DOS CDS DO ARQUIVO
rep = 100
amostra = df.sample(n=rep, replace=True, random_state=2026, ignore_index=True)
tab_sim = pd.crosstab(amostra["resistencia"], amostra["trilhas"])
tab_sim

trilhas      Aprovadas  Reprovadas
resistencia
Alta                73          15
Baixa                8           4

In [15]:
# CALCULAR AS FREQUÊNCIAS DAS QUATRO CATEGORIAS COM PROB
freq_sim = pd.DataFrame({
    "Aprovadas": [
        prob(amostra["A"] & amostra["B"]),
        prob(~amostra["A"] & amostra["B"]),
    ],
    "Reprovadas": [
        prob(amostra["A"] & ~amostra["B"]),
        prob(~amostra["A"] & ~amostra["B"]),
    ],
}, index=["Alta", "Baixa"])
freq_sim.index.name = "resistencia"
freq_sim.columns.name = "trilhas"
freq_sim

trilhas      Aprovadas  Reprovadas
resistencia
Alta              0.73        0.15
Baixa             0.08        0.04

In [16]:
# COMPARAR A FREQUÊNCIA RELATIVA SIMULADA COM A PROBABILIDADE NO LOTE
print("Frequência relativa de A na amostra:", prob(amostra["A"]))
print("Probabilidade de A no lote:", prob(df["A"]))

Frequência relativa de A na amostra: 0.88
Probabilidade de A no lote: 0.84

In [17]:
# COMPARAR AS FREQUÊNCIAS SIMULADAS COM AS PROBABILIDADES DO LOTE.
comparacao = pd.DataFrame({
    "Probabilidade no lote": tab_prob.stack(),
    "Frequência simulada": freq_sim.stack(),
})
comparacao["Diferença"] = comparacao["Frequência simulada"] - comparacao["Probabilidade no lote"]
comparacao

                        Probabilidade no lote  Frequência simulada  Diferença
resistencia trilhas
Alta        Aprovadas                    0.70                 0.73       0.03
            Reprovadas                   0.14                 0.15       0.01
Baixa       Aprovadas                    0.10                 0.08      -0.02
            Reprovadas                   0.06                 0.04      -0.02

A amostra acima foi **gerada artificialmente** com semente 2026 e 100 sorteios com reposição. Compare a frequência relativa simulada com a probabilidade de cada categoria. Não se espera igualdade exata nem aproximação monotônica a cada repetição. A simulação não recupera novos registros reais do lote.

## 5. Regra da soma e exclusão mútua

### 5.1 Regra geral da soma

Ao somar $\mathbb{P}(A)$ e $\mathbb{P}(B)$, os resultados de $A\cap B$ são contados duas vezes. A **regra geral da soma** corrige essa sobreposição (Barbetta; Reis; Bornia, 2010, pp. 97–102; Morettin; Bussab, 2010, pp. 123–125):

$$\mathbb{P}(A\cup B)=\mathbb{P}(A)+\mathbb{P}(B)-\mathbb{P}(A\cap B).
\tag{1.4}
$$

- $\mathbb{P}(A\cup B)$: probabilidade de ao menos um dos eventos.
- $\mathbb{P}(A\cap B)$: probabilidade da ocorrência simultânea.

Na tabela dos CDs, $A$ indica resistência alta e $B$ indica trilhas aprovadas. Calcule $\mathbb{P}(A)$, $\mathbb{P}(B)$, $\mathbb{P}(A\cap B)$ e $\mathbb{P}(A\cup B)$ usando as contagens originais.

In [18]:
# CALCULAR A UNIÃO E CONFERIR A DUPLA CONTAGEM
p_a = prob(df["A"])
p_b = prob(df["B"])
p_ab = prob(df["A"] & df["B"])
p_uniao = p_a + p_b - p_ab
res_soma = pd.Series({
    "P(A)": p_a,
    "P(B)": p_b,
    "P(A∩B)": p_ab,
    "P(A∪B) pela regra": p_uniao,
    "P(A∪B) diretamente": prob(df["A"] | df["B"]),
}, name="probabilidade")
res_soma

P(A)                  0.84
P(B)                  0.80
P(A∩B)                0.70
P(A∪B) pela regra     0.94
P(A∪B) diretamente    0.94
Name: probabilidade, dtype: float64

Obtivemos $\mathbb{P}(A)=0{,}84$, $\mathbb{P}(B)=0{,}80$ e $\mathbb{P}(A\cap B)=0{,}70$. Logo, $\mathbb{P}(A\cup B)=0{,}94$, correspondente a 940 CDs do lote. Somar 0,84 e 0,80 sem retirar a interseção produziria 1,64 e contaria duas vezes os 700 CDs de resistência alta e trilhas aprovadas.

### 5.2 Eventos mutuamente exclusivos

Se os eventos são **mutuamente exclusivos**, $A\cap B=\varnothing$. A regra da soma se reduz a (Barbetta; Reis; Bornia, 2010, pp. 97–102):

$$\mathbb{P}(A\cup B)=\mathbb{P}(A)+\mathbb{P}(B).
\tag{1.5}
$$

Compare as categorias “Alta e Aprovadas” e “Baixa e Reprovadas”. Um único CD selecionado pode pertencer às duas categorias?

In [19]:
# CONFERIR A UNIÃO DE DUAS CATEGORIAS MUTUAMENTE EXCLUSIVAS
n_aa = tab.loc["Alta", "Aprovadas"]
n_br = tab.loc["Baixa", "Reprovadas"]
p_disj = (n_aa + n_br) / n
print(f"P(Alta/Aprovadas ou Baixa/Reprovadas)={p_disj:.2f}")

P(Alta/Aprovadas ou Baixa/Reprovadas)=0.76

As duas categorias são disjuntas para um único CD. A probabilidade da união é 700/1000 + 60/1000 = **0,76**. Já os eventos “resistência alta” e “trilhas aprovadas” se sobrepõem e exigem subtrair a interseção na regra geral da soma.

## 6. Probabilidade condicional e regra do produto

Até aqui, calculamos as probabilidades em relação aos 1.000 CDs do lote. Agora veremos como a informação de que um evento ocorreu muda o conjunto de referência. Depois, usaremos uma probabilidade condicional para calcular a ocorrência conjunta.

### 6.1 Condicionamento

Ao saber que $B$ ocorreu, restringimos a referência aos resultados de $B$. A probabilidade de $A$ **dado** $B$ é a razão entre a probabilidade da interseção e a de $B$ (Barbetta; Reis; Bornia, 2010, pp. 103–105; Morettin; Bussab, 2010, p. 128):

$$\mathbb{P}(A\mid B)=\frac{\mathbb{P}(A\cap B)}{\mathbb{P}(B)},\qquad \mathbb{P}(B)>0.
\tag{1.6}
$$

- $\mathbb{P}(A\mid B)$: probabilidade de resistência alta entre os CDs com trilhas aprovadas.
- $\mathbb{P}(B)$: probabilidade do evento condicionante, que precisa ser positiva.

Use a tabela original para calcular $\mathbb{P}(A\mid B)$ e $\mathbb{P}(B\mid A)$. A primeira razão considera 800 CDs com trilhas aprovadas. A segunda considera 840 CDs com resistência alta. As contagens agregadas são suficientes para as duas razões, desde que cada CD do lote tenha a mesma probabilidade de ser escolhido.

In [20]:
# COMPARAR OS DOIS SENTIDOS DO CONDICIONAMENTO
p_a_dado_b = p_ab / p_b
p_b_dado_a = p_ab / p_a
cond = pd.Series({
    "P(A|B)": p_a_dado_b,
    "P(B|A)": p_b_dado_a,
}, name="probabilidade")
cond

P(A|B)    0.875000
P(B|A)    0.833333
Name: probabilidade, dtype: float64

Entre os 800 CDs com trilhas aprovadas, 700 têm resistência alta. Assim, $\mathbb{P}(A\mid B)=700/800=0{,}875$. Entre os 840 CDs com resistência alta, 700 têm trilhas aprovadas. Assim, $\mathbb{P}(B\mid A)=700/840\approx0{,}8333$. As condicionais inversas diferem porque os conjuntos de referência têm tamanhos diferentes.

Em `prob_cond(A, B)`, a expressão `A[B]` seleciona os valores de A somente nos registros que satisfazem B. A função `prob` passa a dividir pelo tamanho desse subconjunto. As duas séries devem representar os mesmos indivíduos. Se nenhum registro satisfizer B, a condicional não pode ser calculada nesse conjunto.

In [21]:
# RESTRINGIR O CONJUNTO DE REFERÊNCIA AO EVENTO CONDICIONANTE
def prob_cond(A, B):
    """Calcula a proporção de A entre os registros que satisfazem B."""
    validar_evento(A)
    validar_evento(B)
    if not A.index.equals(B.index):
        raise ValueError("A e B devem ter os mesmos índices e ordem.")
    if not B.any():
        raise ValueError("Não há registros que satisfaçam B.")
    return prob(A[B])

In [22]:
# CONFERIR OS DOIS SENTIDOS DO CONDICIONAMENTO PELA SELEÇÃO DOS REGISTROS
pd.Series({
    "P(A|B) pela função": prob_cond(df["A"], df["B"]),
    "P(B|A) pela função": prob_cond(df["B"], df["A"]),
}, name="probabilidade")

P(A|B) pela função    0.875000
P(B|A) pela função    0.833333
Name: probabilidade, dtype: float64

### 6.2 Regra geral do produto

Partimos da Equação (1.6), válida quando $\mathbb{P}(B)>0$:

$$
\mathbb{P}(A\mid B)=\frac{\mathbb{P}(A\cap B)}{\mathbb{P}(B)}.
$$

Multiplicamos os dois lados por $\mathbb{P}(B)$:

$$
\mathbb{P}(B)\mathbb{P}(A\mid B)=\mathbb{P}(A\cap B).
$$

Invertendo os lados da igualdade, chegamos à **regra geral do produto** (Barbetta; Reis; Bornia, 2010, pp. 106–109; Morettin; Bussab, 2010, pp. 128–130):

$$\mathbb{P}(A\cap B)=\mathbb{P}(B)\mathbb{P}(A\mid B).
\tag{1.7}
$$

A regra não pressupõe independência.

In [23]:
# CONFERIR A REGRA DO PRODUTO NO LOTE DE 1.000 CDS
print("P(B)P(A|B):", round(prob(df["B"]) * prob_cond(df["A"], df["B"]), 2))
print("P(A∩B):", prob(df["A"] & df["B"]))

P(B)P(A|B): 0.7
P(A∩B): 0.7

Considere uma caixa com 4 CDs de baixa resistência e 8 de alta resistência. Retiramos ao acaso dois CDs, um após o outro, sem reposição, e registramos suas resistências. Esta caixa hipotética troca apenas as cores dos cartões do Exemplo 4.9 por categorias de resistência. Ela não representa o CSV de 1.000 CDs usado nas seções anteriores (Barbetta; Reis; Bornia, 2010, pp. 105–107).

- $L_i$: resistência baixa na retirada $i$.
- $H_i$: resistência alta na retirada $i$.

**a)** Qual é a probabilidade de os dois CDs terem baixa resistência? Aplicamos a regra do produto:

$$
\begin{aligned}
\mathbb{P}(L_1\cap L_2)
&= \mathbb{P}(L_1)\mathbb{P}(L_2\mid L_1) \\
&= \frac{4}{12}\cdot\frac{3}{11} = \frac{1}{11} \approx 0{,}090909.
\end{aligned}
$$

In [24]:
# REGISTRAR AS QUANTIDADES DA CAIXA HIPOTÉTICA
n_l = 4
n_h = 8
n_c = n_l + n_h
print(f"Baixa: {n_l} | Alta: {n_h} | Total: {n_c}")

Baixa: 4 | Alta: 8 | Total: 12

In [25]:
# APLICAR A REGRA DO PRODUTO A DUAS RESISTÊNCIAS BAIXAS
p_ll = (n_l / n_c) * ((n_l - 1) / (n_c - 1))
print(f"P(L₁∩L₂) = {p_ll:.6f}")

P(L₁∩L₂) = 0.090909

O segundo fator considera os CDs restantes após a primeira retirada. Se o primeiro tinha baixa resistência, restam 3 CDs dessa categoria entre 11 CDs.

**b)** Como atribuir probabilidades aos quatro pares ordenados de **categorias observadas**: $(L_1,L_2)$, $(L_1,H_2)$, $(H_1,L_2)$ e $(H_1,H_2)$? Confira se a soma é 1.

Aplicamos a regra do produto a cada par ordenado:

$$
\begin{aligned}
\mathbb{P}(L_1\cap L_2)
&= \mathbb{P}(L_1)\mathbb{P}(L_2\mid L_1)
= \frac{4}{12}\cdot\frac{3}{11} = \frac{1}{11} \approx 0{,}090909, \\
\mathbb{P}(L_1\cap H_2)
&= \mathbb{P}(L_1)\mathbb{P}(H_2\mid L_1)
= \frac{4}{12}\cdot\frac{8}{11} = \frac{8}{33} \approx 0{,}242424, \\
\mathbb{P}(H_1\cap L_2)
&= \mathbb{P}(H_1)\mathbb{P}(L_2\mid H_1)
= \frac{8}{12}\cdot\frac{4}{11} = \frac{8}{33} \approx 0{,}242424, \\
\mathbb{P}(H_1\cap H_2)
&= \mathbb{P}(H_1)\mathbb{P}(H_2\mid H_1)
= \frac{8}{12}\cdot\frac{7}{11} = \frac{14}{33} \approx 0{,}424242.
\end{aligned}
$$

Os quatro casos são mutuamente exclusivos e esgotam as possibilidades de categorias observadas:

$$
\frac{1}{11}+\frac{8}{33}+\frac{8}{33}+\frac{14}{33}=1.
$$

In [26]:
# CALCULAR AS PROBABILIDADES DOS QUATRO PARES ORDENADOS
p_lh = (n_l / n_c) * (n_h / (n_c - 1))
p_hl = (n_h / n_c) * (n_l / (n_c - 1))
p_hh = (n_h / n_c) * ((n_h - 1) / (n_c - 1))
seq = pd.Series({"Baixa, baixa": p_ll, "Baixa, alta": p_lh, "Alta, baixa": p_hl, "Alta, alta": p_hh}, name="probabilidade")
seq

Baixa, baixa    0.090909
Baixa, alta     0.242424
Alta, baixa     0.242424
Alta, alta      0.424242
Name: probabilidade, dtype: float64

In [27]:
# CONFERIR A SOMA DOS QUATRO PARES ORDENADOS
print(f"Soma = {seq.sum():.6f}")

Soma = 1.000000

**c)** Qual é a probabilidade de ocorrer exatamente um CD de baixa resistência nas duas retiradas?

Como os casos $(L_1,H_2)$ e $(H_1,L_2)$ são mutuamente exclusivos, somamos suas probabilidades e aplicamos a regra do produto a cada caso:

$$
\begin{aligned}
\mathbb{P}(\text{exatamente uma baixa})
&= \mathbb{P}(L_1\cap H_2) + \mathbb{P}(H_1\cap L_2) \\
&= \mathbb{P}(L_1)\mathbb{P}(H_2\mid L_1) + \mathbb{P}(H_1)\mathbb{P}(L_2\mid H_1) \\
&= \frac{4}{12}\cdot\frac{8}{11} + \frac{8}{12}\cdot\frac{4}{11} = \frac{16}{33} \approx 0{,}484848.
\end{aligned}
$$

In [28]:
# SOMAR OS DOIS PARES COM EXATAMENTE UMA RESISTÊNCIA BAIXA
p_um_l = p_lh + p_hl
print(f"P(exatamente uma baixa) = {p_um_l:.6f}")

P(exatamente uma baixa) = 0.484848

**d)** Se retirarmos três CDs sem reposição, qual é a probabilidade de os dois primeiros terem alta resistência e o terceiro ter baixa resistência?

Aplicamos a regra do produto às três retiradas, atualizando as quantidades após cada retirada:

$$
\begin{aligned}
\mathbb{P}(H_1\cap H_2\cap L_3)
&= \mathbb{P}(H_1)\mathbb{P}(H_2\mid H_1)\mathbb{P}(L_3\mid H_1\cap H_2) \\
&= \frac{8}{12}\cdot\frac{7}{11}\cdot\frac{4}{10} = \frac{28}{165} \approx 0{,}169697.
\end{aligned}
$$

In [29]:
# APLICAR O PRODUTO A TRÊS RETIRADAS SEM REPOSIÇÃO
p_hhl = (n_h / n_c) * ((n_h - 1) / (n_c - 1)) * (n_l / (n_c - 2))
print(f"P(alta, alta, baixa) = {p_hhl:.6f}")

P(alta, alta, baixa) = 0.169697

Os quatro pares ordenados esgotam as **categorias observadas** nas duas retiradas, mas não têm probabilidades iguais. Exatamente uma resistência baixa ocorre nos pares $(L_1,H_2)$ e $(H_1,L_2)$. No item d, após duas resistências altas, restam 4 CDs de baixa resistência entre 10 CDs.

Os pares baixa–alta e alta–baixa têm a mesma probabilidade porque ambos correspondem a $4\times8=32$ pares de CDs distintos entre $12\times11=132$ pares ordenados equiprováveis. A ordem altera o primeiro fator, mas os produtos são iguais: $(4/12)(8/11)=(8/12)(4/11)=8/33$.

## 7. Partições e probabilidade total

> **Como atualizar uma probabilidade após observar uma nova evidência?**

### 7.1 Partição do espaço amostral

Uma **partição** divide o espaço amostral em eventos que não se sobrepõem e que, juntos, cobrem todos os resultados possíveis. Por exemplo, ao lançar um dado, “face par” e “face ímpar” formam uma partição. Cada resultado pertence a exatamente um dos eventos (Barbetta; Reis; Bornia, 2010, pp. 110–111).

$$
E_i\cap E_j=\varnothing\quad(i\ne j),\qquad \bigcup_{i=1}^{k}E_i=\Omega.\tag{1.8}
$$

Aqui, $\Omega$ é o espaço amostral, $E_1,\ldots,E_k$ são os eventos, $\cap$ representa a interseção, $\cup$ representa a união e $\varnothing$ é o conjunto vazio. Para usar uma probabilidade condicionada a $E_i$, exigimos $\mathbb{P}(E_i)>0$.

![Partição do espaço amostral e decomposição de um evento](https://raw.githubusercontent.com/carubbi/MQ/main/notebooks/assets/imgs/u2_s01/barbetta_figura_4_6.png)

**Figura 2 - Partição do espaço amostral e decomposição de um evento.** As regiões $E_1,\ldots,E_7$ são mutuamente exclusivas e cobrem o universo. O evento $F$ atravessa alguns desses eventos, formando as parcelas disjuntas $F\cap E_i$. Assim, sua probabilidade pode ser obtida pela soma das probabilidades dessas parcelas, sem dupla contagem. Fonte: reprodução da Figura 4.6 (BARBETTA; REIS; BORNIA, 2010, p. 111).

Os eventos $E_i$ e a evidência $F$ seguem a mesma notação no diagrama e nas fórmulas deste notebook. Essa decomposição fundamenta a regra da probabilidade total da seção 7.2.

### 7.2 Regra da probabilidade total

Se a evidência $F$ pode ocorrer em qualquer evento, podemos separá-la em parcelas disjuntas (Barbetta; Reis; Bornia, 2010, pp. 110–111).

$$
F=\bigcup_{i=1}^{k}(F\cap E_i).\tag{1.9}
$$

Para calcular a probabilidade de cada parcela, retomamos a definição de probabilidade condicional. Como $\mathbb{P}(E_i)>0$:

$$
\mathbb{P}(F\mid E_i)=\frac{\mathbb{P}(F\cap E_i)}{\mathbb{P}(E_i)}.
$$

Multiplicando os dois lados por $\mathbb{P}(E_i)$ e isolando a probabilidade da interseção, obtemos a **regra do produto**, conforme a demonstração original (BARBETTA; REIS; BORNIA, 2010, p. 105):

$$
\mathbb{P}(F\cap E_i)=\mathbb{P}(E_i)\mathbb{P}(F\mid E_i).
$$

Essa regra não pressupõe independência. Como as parcelas $F\cap E_i$ são mutuamente exclusivas, somamos suas probabilidades. Substituindo a regra do produto em cada parcela, chegamos à **regra da probabilidade total** (Barbetta; Reis; Bornia, 2010, p. 111):

$$
\begin{aligned}
\mathbb{P}(F)
&=\sum_{i=1}^{k}\mathbb{P}(F\cap E_i)\\
&=\sum_{i=1}^{k}\mathbb{P}(E_i)\mathbb{P}(F\mid E_i).
\end{aligned}\tag{1.10}
$$

Aqui, $\mathbb{P}(E_i)$ é a probabilidade inicial do evento, $\mathbb{P}(F\mid E_i)$ é a probabilidade da evidência dentro dele e $\mathbb{P}(F)$ é a probabilidade da evidência considerando todos os eventos. Não basta somar as probabilidades condicionais. Cada uma deve receber o peso do respectivo evento.

**APLICAÇÃO**: Entre profissionais de psicologia, 60% atuam na área clínica, 20% na empresarial e 20% em outras áreas. Usam regularmente o computador 10% dos profissionais da área clínica, 70% da empresarial e 40% das outras áreas. Qual é a probabilidade de selecionar uma pessoa que **não** usa regularmente o computador? Os percentuais são os dados do enunciado, não observações individuais (Pinheiro et al., 2009, p. 94).

| Área | Probabilidade inicial | $\mathbb{P}(\text{usa}\mid\text{área})$ | $\mathbb{P}(\text{não usa}\mid\text{área})$ |
| --- | ---: | ---: | ---: |
| Clínica | 0,60 | 0,10 | 0,90 |
| Empresarial | 0,20 | 0,70 | 0,30 |
| Outras | 0,20 | 0,40 | 0,60 |

Antes de executar o código, identifique a partição e estime se o resultado deve ficar acima ou abaixo de 0,50.

**Cálculo manual.** As contribuições para “não usa” são $0{,}60\times0{,}90=0{,}54$ na área clínica, $0{,}20\times0{,}30=0{,}06$ na empresarial e $0{,}20\times0{,}60=0{,}12$ nas outras áreas. A probabilidade total é $0{,}54+0{,}06+0{,}12=0{,}72$.

**Aplicação com dados sintéticos.** O CSV `u1_a12_psicologos.csv` contém 1.000 registros artificiais, já embaralhados com semente 2026, que reproduzem exatamente os percentuais do enunciado. As colunas são `area` e `usa_pc`; `True` indica uso de computador e `False`, não uso. As linhas não são observações coletadas nem registros individuais publicados no livro. Cada pessoa artificial pertence a uma única área: clínica, empresarial ou outras. Esses três eventos formam a partição; $F$ é o evento “não usa computador”.

In [30]:
# CARREGAR O CSV SINTÉTICO PUBLICADO NO GITHUB.
import pandas as pd
from math import isclose

url_psicologos = "https://raw.githubusercontent.com/carubbi/MQ/e1af216920967e8af3945debdd6d4e61cdad002f/notebooks/assets/data/u1_a12_psicologos.csv"
df = pd.read_csv(url_psicologos)
df.head()

      area  usa_pc
0  Clínica   False
1  Clínica   False
2  Clínica   False
3  Clínica   False
4  Clínica   False

In [31]:
# RECONSTRUIR AS CONTAGENS POR ÁREA E USO DE COMPUTADOR.
tab = pd.crosstab(df["area"], df["usa_pc"])
tab = tab.rename(columns={False: "nao_usa", True: "usa"})
tab["n"] = tab["nao_usa"] + tab["usa"]
tab

usa_pc       nao_usa  usa    n
area
Clínica          540   60  600
Empresarial       60  140  200
Outras           120   80  200

In [32]:
# CALCULAR AS PROBABILIDADES INICIAIS E CONDICIONAIS PELAS CONTAGENS.
tab["p_area"] = tab["n"] / len(df)
tab["p_usa"] = tab["usa"] / tab["n"]
tab["p_nao_usa"] = tab["nao_usa"] / tab["n"]
tab[["p_area", "p_usa", "p_nao_usa"]]

usa_pc       p_area  p_usa  p_nao_usa
area
Clínica         0.6    0.1        0.9
Empresarial     0.2    0.7        0.3
Outras          0.2    0.4        0.6

In [33]:
# CALCULAR A CONTRIBUIÇÃO CONJUNTA DE CADA ÁREA.
tab["p_area_e_nao_usa"] = tab["p_area"] * tab["p_nao_usa"]
tab[["p_area", "p_nao_usa", "p_area_e_nao_usa"]]

usa_pc       p_area  p_nao_usa  p_area_e_nao_usa
area
Clínica         0.6        0.9              0.54
Empresarial     0.2        0.3              0.06
Outras          0.2        0.6              0.12

In [34]:
# SOMAR AS CONTRIBUIÇÕES PARA OBTER A PROBABILIDADE TOTAL.
p_nao = float(tab["p_area_e_nao_usa"].sum())
print(f"P(não usa computador) = {p_nao:.2f} ({p_nao:.0%})")

P(não usa computador) = 0.72 (72%)

In [35]:
# COMPARAR COM A CONTAGEM DIRETA E A SOLUÇÃO MANUAL.
p_nao_direta = (~df["usa_pc"]).mean()
pd.Series({
    "P(não usa) pela probabilidade total": p_nao,
    "P(não usa) pela contagem direta": p_nao_direta,
    "Confere com o cálculo manual": isclose(p_nao, 0.72),
})

P(não usa) pela probabilidade total    0.72
P(não usa) pela contagem direta        0.72
Confere com o cálculo manual           True
dtype: object

As contagens do CSV reproduzem 600 registros da área clínica, 200 da empresarial e 200 das outras áreas. Entre eles, 540, 60 e 120, respectivamente, não usam computador. As contribuições conjuntas são $0{,}54$, $0{,}06$ e $0{,}12$; sua soma fornece $0{,}72$. A contagem direta confirma $720/1.000=0{,}72$: **72% não usam computador** no cenário do exercício.

## 8. Teorema de Bayes e probabilidade inicial

### 8.1 Atualização da probabilidade

Seja $E$ o **evento de interesse** e $F$ a **evidência observada**, com $\mathbb{P}(E)>0$ e $\mathbb{P}(F)>0$. A probabilidade **a priori** é $\mathbb{P}(E)$. Após observar $F$, a probabilidade **a posteriori** é $\mathbb{P}(E\mid F)$ (MORETTIN; BUSSAB, 2010, pp. 116–118).

Pela definição de probabilidade condicional e pela regra do produto (BARBETTA; REIS; BORNIA, 2010, pp. 105, 112):

$$
\begin{aligned}
\mathbb{P}(E\mid F)&=\frac{\mathbb{P}(E\cap F)}{\mathbb{P}(F)},\\
\mathbb{P}(E\cap F)&=\mathbb{P}(E)\mathbb{P}(F\mid E).
\end{aligned}
$$

Substituindo a segunda identidade na primeira:

$$
\mathbb{P}(E\mid F)=\frac{\mathbb{P}(E)\mathbb{P}(F\mid E)}{\mathbb{P}(F)}.\tag{1.11}
$$

Pela probabilidade total da Equação (1.10):

$$
\mathbb{P}(E\mid F)=\frac{\mathbb{P}(E)\mathbb{P}(F\mid E)}{\sum_{i=1}^{k}\mathbb{P}(E_i)\mathbb{P}(F\mid E_i)}.\tag{1.12}
$$

**Aplicação — probabilidade posterior da área clínica (exercício 3.8_P).**

Usando o mesmo CSV sintético da aplicação anterior, qual é a probabilidade de uma pessoa atuar na área clínica, sabendo que ela **não** usa regularmente o computador? Fonte: adaptação de Pinheiro et al., 2009, p. 94.

**Cálculo manual.** A contribuição conjunta da área clínica para o não uso é $0{,}60\times0{,}90=0{,}54$. A probabilidade total de não uso, calculada no item a, é $0{,}72$. Logo, $\mathbb{P}(\text{clínica}\mid\text{não usa})=0{,}54/0{,}72=0{,}75$. Já $\mathbb{P}(\text{não usa}\mid\text{clínica})=0{,}90$. A inversão muda o evento condicionante.

In [36]:
# CALCULAR A PROBABILIDADE DA ÁREA CLÍNICA APÓS OBSERVAR O NÃO USO
p_clin_nao = float(tab.loc["Clínica", "p_area_e_nao_usa"])
p_clin_dado_nao = p_clin_nao / p_nao
round(p_clin_dado_nao, 2)

0.75

In [37]:
# Conferir o cálculo manual do item b
isclose(p_clin_dado_nao, 0.75)

True

O código confirma $0{,}75$. Ao condicionar por **não usar computador**, consideramos pessoas das três áreas e calculamos a probabilidade de pertencer à **área clínica**. Por isso, essa probabilidade difere de $\mathbb{P}(\text{não usa}\mid\text{clínica})=0{,}90$.

**APLICAÇÃO**: Um teste de gravidez tem **sensibilidade** de 0,98 e **especificidade** de 0,95. A probabilidade inicial de gravidez no cenário do enunciado é 0,20. Calcule a probabilidade de gravidez após resultado positivo e a probabilidade de não gravidez após resultado negativo (Pinheiro et al., 2009, p. 94).

- $G$: gravidez. $G^c$: não gravidez.
- $\mathrm{pos}$: resultado positivo. $\mathrm{neg}$: resultado negativo.
- Sensibilidade: $\mathbb{P}(\mathrm{pos}\mid G)=0{,}98$.
- Especificidade: $\mathbb{P}(\mathrm{neg}\mid G^c)=0{,}95$.

As probabilidades complementares são $\mathbb{P}(\mathrm{pos}\mid G^c)=0{,}05$ e $\mathbb{P}(\mathrm{neg}\mid G)=0{,}02$. O valor inicial de 0,20 é uma premissa deste exercício, não uma prevalência geral nem uma recomendação clínica.

$$
\begin{aligned}
\mathbb{P}(G\mid \mathrm{pos})&=\frac{\mathbb{P}(\mathrm{pos}\mid G)\mathbb{P}(G)}{\mathbb{P}(\mathrm{pos})}.
\end{aligned}\tag{1.13}
$$

$$
\begin{aligned}
\mathbb{P}(G^c\mid \mathrm{neg})&=\frac{\mathbb{P}(\mathrm{neg}\mid G^c)\mathbb{P}(G^c)}{\mathbb{P}(\mathrm{neg})}.
\end{aligned}\tag{1.14}
$$

Os símbolos $G$, $G^c$, $\mathrm{pos}$ e $\mathrm{neg}$ estão definidos acima. Os denominadores $\mathbb{P}(\mathrm{pos})$ e $\mathbb{P}(\mathrm{neg})$ incluem, respectivamente, todos os resultados positivos e todos os resultados negativos.

**Cálculo manual.** Para o resultado positivo, $\mathbb{P}(\mathrm{pos})=0{,}98\times0{,}20+0{,}05\times0{,}80=0{,}236$ e $\mathbb{P}(G\mid \mathrm{pos})=0{,}196/0{,}236\approx0{,}8305$. Para o negativo, $\mathbb{P}(\mathrm{neg})=0{,}02\times0{,}20+0{,}95\times0{,}80=0{,}764$ e $\mathbb{P}(G^c\mid \mathrm{neg})=0{,}760/0{,}764\approx0{,}9948$.

In [38]:
# CARREGAR O CSV SINTÉTICO DO TESTE DE GRAVIDEZ PUBLICADO NO GITHUB.
url_teste = "https://raw.githubusercontent.com/carubbi/MQ/e1af216920967e8af3945debdd6d4e61cdad002f/notebooks/assets/data/u1_a12_teste_gravidez.csv"
df_t = pd.read_csv(url_teste)
df_t.head()

    grav    pos
0  False  False
1   True   True
2  False  False
3   True   True
4  False   True

In [39]:
# RECONSTRUIR AS CONTAGENS POR CONDIÇÃO E RESULTADO DO TESTE.
tab_t = pd.crosstab(df_t["grav"], df_t["pos"])
tab_t = tab_t.rename(index={False: "Não gravidez", True: "Gravidez"},
                     columns={False: "Negativo", True: "Positivo"})
tab_t

pos           Negativo  Positivo
grav
Não gravidez       760        40
Gravidez             4       196

In [40]:
# OBTER A PROBABILIDADE A PRIORI E AS PROBABILIDADES CONDICIONAIS.
n_t = len(df_t)
n_g = tab_t.loc["Gravidez"].sum()
n_nao_g = tab_t.loc["Não gravidez"].sum()

p_g = n_g / n_t
p_nao_g = 1 - p_g
p_pos_g = tab_t.loc["Gravidez", "Positivo"] / n_g
p_neg_nao_g = tab_t.loc["Não gravidez", "Negativo"] / n_nao_g
p_pos = tab_t["Positivo"].sum() / n_t
p_neg = tab_t["Negativo"].sum() / n_t

pd.Series({
    "P(G)": p_g,
    "P(não G)": p_nao_g,
    "P(pos)": p_pos,
    "P(neg)": p_neg,
    "P(pos | G) ou sensibilidade": p_pos_g,
    "P(neg | não G) ou especificidade": p_neg_nao_g,
})

P(G)                                0.200
P(não G)                            0.800
P(pos)                              0.236
P(neg)                              0.764
P(pos | G) ou sensibilidade         0.980
P(neg | não G) ou especificidade    0.950
dtype: float64

In [41]:
# APLICAR BAYES AO RESULTADO POSITIVO.
p_g_pos = p_g * p_pos_g / p_pos
print(f"P(gravidez | positivo) = {p_g_pos:.4f} ({p_g_pos:.2%})")

P(gravidez | positivo) = 0.8305 (83.05%)

In [42]:
# APLICAR BAYES AO RESULTADO NEGATIVO.
p_nao_g_neg = p_nao_g * p_neg_nao_g / p_neg
print(f"P(não gravidez | negativo) = {p_nao_g_neg:.4f} ({p_nao_g_neg:.2%})")

P(não gravidez | negativo) = 0.9948 (99.48%)

### 8.2 Efeito da taxa-base

**Comparação hipotética.** Mantemos sensibilidade e especificidade iguais às do exercício, mas trocamos a probabilidade inicial de 0,20 por 0,01. Essa troca define outro cenário.

In [43]:
# COMPARAR DOIS VALORES DA PROBABILIDADE INICIAL.
p_g_alt = 0.01
p_nao_g_alt = 1 - p_g_alt
p_pos_nao_g = 1 - p_neg_nao_g
p_pos_alt = p_g_alt * p_pos_g + p_nao_g_alt * p_pos_nao_g
p_g_pos_alt = p_g_alt * p_pos_g / p_pos_alt

# ORGANIZAR A COMPARAÇÃO DOS CENÁRIOS.
tab = pd.DataFrame({
    "P(G) inicial": [p_g, p_g_alt],
    "P(G | positivo)": [p_g_pos, p_g_pos_alt],
})
tab

   P(G) inicial  P(G | positivo)
0          0.20         0.830508
1          0.01         0.165261

Com probabilidade inicial de $0{,}20$, a posterior após resultado positivo é aproximadamente $0{,}8305$. No cenário hipotético com probabilidade inicial de $0{,}01$, ela cai para aproximadamente $0{,}1653$. O mesmo teste produz posteriores diferentes porque a probabilidade inicial mudou.

## 9. Independência

### 9.1 Verificação da independência

Dois eventos são **independentes** quando saber que um ocorreu não altera a probabilidade do outro. Para dois eventos, podemos verificar a seguinte condição (Barbetta; Reis; Bornia, 2010, pp. 109–110; Morettin; Bussab, 2010, pp. 129–131):

$$\mathbb{P}(A\cap B)=\mathbb{P}(A)\mathbb{P}(B).
\tag{1.15}
$$

Esta fatoração é uma condição a verificar, não um atalho automático. Eventos mutuamente exclusivos de probabilidades positivas não são independentes: a ocorrência de um impede a do outro.

Na tabela a seguir, os números **já são probabilidades** (Morettin; Bussab, 2010, problema 21, p. 132):

| | $B$ | $B^{c}$ | Total |
| --- | ---: | ---: | ---: |
| $A$ | 0,04 | 0,06 | 0,10 |
| $A^{c}$ | 0,08 | 0,82 | 0,90 |
| Total | 0,12 | 0,88 | 1,00 |

Verifique a independência de $A$ e $B$ comparando a célula conjunta com o produto das marginais.

In [44]:
# MOSTRAR A TABELA DE PROBABILIDADES DE MORETTIN E BUSSAB
tab_m = pd.DataFrame(
    [[0.04, 0.06], [0.08, 0.82]],
    index=["A", "A_c"],
    columns=["B", "B_c"],
)
tab_m

        B   B_c
A    0.04  0.06
A_c  0.08  0.82

In [45]:
# COMPARAR A CONJUNTA COM O PRODUTO DAS MARGINAIS
p_a_m = tab_m.loc["A"].sum()
p_b_m = tab_m["B"].sum()
p_ab_m = tab_m.loc["A", "B"]
print(f"P(A∩B)={p_ab_m:.3f} | P(A)P(B)={p_a_m * p_b_m:.3f}")

P(A∩B)=0.040 | P(A)P(B)=0.012

A célula conjunta vale 0,04. O produto das marginais é $0{,}10\times0{,}12=0{,}012$. Como não são iguais, **$A$ e $B$ não são independentes**. A comparação usa probabilidades fornecidas na tabela, não frequências a serem estimadas.

A conclusão não depende de qual evento ocorre primeiro: a condição de independência compara a conjunta com o produto das marginais e é simétrica em $A$ e $B$. Também podemos verificar $P(A\mid B)=0{,}04/0{,}12\approx0{,}3333$, diferente de $P(A)=0{,}10$.

## 10. Estudo e exercícios

### 10.1 Materiais didáticos

- Barbetta, Reis e Bornia (2010), seções 4.1–4.3, pp. 94–110: eventos, soma, condicionamento e independência de dois eventos. É a leitura principal.
- Barbetta, Reis e Bornia (2010), Exemplo 4.9, pp. 105–107: retiradas sem reposição e regra do produto. A caixa de 12 CDs troca somente as categorias dos cartões originais.
- Morettin e Bussab (2010), Exemplo 5.13, p. 131: dois componentes em série e paralelo, com independência declarada.
- PINHEIRO et al. (2009), Exemplo 3.8, pp. 97–100: leitura complementar para distinguir soma e produto.
- BARBETTA; REIS; BORNIA (2010), seção 4.4, pp. 110–111 do livro: partição e probabilidade total.
- BARBETTA; REIS; BORNIA (2010), seção 4.5, p. 112 do livro: Teorema de Bayes.
- MORETTIN; BUSSAB (2010), seção 5.4, pp. 116–120 do livro: probabilidade inicial, posterior e atualização.

### 10.2 Exercícios indicados

- Morettin e Bussab (2010), problema 8, p. 127: representar “A sem B”, “exatamente um” e “nenhum”.
- PINHEIRO et al. (2009), exercício 3.2_P, p. 109: tentativas entre seis ordens sem repetir. Justifique o produto condicional.
- Morettin e Bussab (2010), problema 18, p. 132: condicionamento no dado viciado.
- Morettin e Bussab (2010), problema 21, p. 132: conferir independência na tabela de probabilidades.
- PINHEIRO et al. (2009), exercícios 3.3_P, pp. 109–110, e 3.4_P, p. 110: complemento, união e independência sob as hipóteses dadas.
- NAVIDI (2024), seção 2.3, exercício 21, p. 109: discutir independência e causa comum de falha.
- PINHEIRO et al. (2009), exercício 3.8_P, p. 94 do livro: calcule a probabilidade de não usar computador nas três áreas e depois a probabilidade da área clínica dado o não uso. Explique por que os denominadores dos itens a e b são diferentes.
- PINHEIRO et al. (2009), exercício 3.9_P, p. 94 do livro: calcule as duas probabilidades posteriores do teste. Indique as probabilidades complementares usadas em cada denominador.

## 11. Referências

1. BARBETTA, Pedro Alberto; REIS, Marcelo Menezes; BORNIA, Antonio Cezar. *Estatística para cursos de engenharia e informática*. 3. ed. São Paulo: Atlas, 2010.
2. PINHEIRO, João Ismael D. et al. *Estatística básica: a arte de trabalhar com dados*. Rio de Janeiro: Elsevier, 2009.
3. MORETTIN, Pedro A.; BUSSAB, Wilton O. *Estatística básica*. 6. ed. São Paulo: Saraiva, 2010.
4. ESCOVEDO, Tatiana; MARQUES, Thiago; KALINOWSKI, Marcos. *Introdução à estatística para ciência de dados*. São Paulo: Casa do Código, 2025.
5. MONTGOMERY, Douglas C.; RUNGER, George C. *Applied Statistics and Probability for Engineers*. 7. ed. Hoboken: Wiley, 2018.
6. NAVIDI, William. *Statistics for Engineers and Scientists*. 6. ed. New York: McGraw Hill, 2024.
7. SEEING THEORY. **Compound probability**. [S. l.], [s. d.]. Disponível em: https://seeing-theory.brown.edu/compound-probability/index.html. Acesso em: 8 out. 2026.