# **Aula 7**

## Importação das bibiliotecas

In [ ]:
# Importando a bilioteca de maipulação de dataframes
import pandas as pd
print(pd.__version__)

2.2.3

## Carregamento do conjunto de dados

In [ ]:
# Definir o endereço e exibir as cinco primeiras observações
url = '/content/penguins_raw.csv'
url = 'https://raw.githubusercontent.com/allisonhorst/palmerpenguins/master/inst/extdata/penguins_raw.csv'
df_raw = pd.read_csv(url)
df_raw.head()

,studyName,Sample Number,Species,Region,Island,Stage,Individual ID,Clutch Completion,Date Egg,Culmen Length (mm),Culmen Depth (mm),Flipper Length (mm),Body Mass (g),Sex,Delta 15 N (o/oo),Delta 13 C (o/oo),Comments
0,PAL0708,1,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A1,Yes,2007-11-11,39.1,18.7,181.0,3750.0,MALE,NaN,NaN,Not enough blood for isotopes.
1,PAL0708,2,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A2,Yes,2007-11-11,39.5,17.4,186.0,3800.0,FEMALE,8.94956,-24.69454,NaN
2,PAL0708,3,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N2A1,Yes,2007-11-16,40.3,18.0,195.0,3250.0,FEMALE,8.36821,-25.33302,NaN
3,PAL0708,4,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N2A2,Yes,2007-11-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adult not sampled.
4,PAL0708,5,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N3A1,Yes,2007-11-16,36.7,19.3,193.0,3450.0,FEMALE,8.76651,-25.32426,NaN

In [ ]:
# Verificando informações dos dados
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   studyName            344 non-null    object
 1   Sample Number        344 non-null    int64
 2   Species              344 non-null    object
 3   Region               344 non-null    object
 4   Island               344 non-null    object
 5   Stage                344 non-null    object
 6   Individual ID        344 non-null    object
 7   Clutch Completion    344 non-null    object
 8   Date Egg             344 non-null    object
 9   Culmen Length (mm)   342 non-null    float64
 10  Culmen Depth (mm)    342 non-null    float64
 11  Flipper Length (mm)  342 non-null    float64
 12  Body Mass (g)        342 non-null    float64
 13  Sex                  333 non-null    object
 14  Delta 15 N (o/oo)    330 non-null    float64
 15  Delta 13 C (o/oo)    331 non-null    float64
 16  Comments             54 non-null     object
dtypes: float64(6), int64(1), object(10)
memory usage: 45.8+ KB

In [ ]:
# Informando as dimensões
print(df_raw.shape)

(344, 17)

## Pré-processamento do dado

In [ ]:
# Filtrando das colunas desejadas
cols = df_raw.columns.to_list()
cols_sel = cols[2:5] + cols[8:-3]
df = df_raw[cols_sel].copy()
df.head()

,Species,Region,Island,Date Egg,Culmen Length (mm),Culmen Depth (mm),Flipper Length (mm),Body Mass (g),Sex
0,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,2007-11-11,39.1,18.7,181.0,3750.0,MALE
1,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,2007-11-11,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,2007-11-16,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,2007-11-16,NaN,NaN,NaN,NaN,NaN
4,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,2007-11-16,36.7,19.3,193.0,3450.0,FEMALE

In [ ]:
# Padronizando os rótulos das colunas
cols_limpas = []
for i,_ in enumerate(cols_sel):
    cols_sel[i] = cols_sel[i].replace(' ', '_').upper()
    if cols_sel[i].endswith(')'):
        cols_partes = cols_sel[i].split('_')[:-1]
        cols_limpas.append('_'.join(cols_partes))

cols_limpas = cols_sel[:4] + cols_limpas + [cols_sel[-1]]
df.columns = cols_limpas

df.head()

,SPECIES,REGION,ISLAND,DATE_EGG,CULMEN_LENGTH,CULMEN_DEPTH,FLIPPER_LENGTH,BODY_MASS,SEX
0,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,2007-11-11,39.1,18.7,181.0,3750.0,MALE
1,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,2007-11-11,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,2007-11-16,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,2007-11-16,NaN,NaN,NaN,NaN,NaN
4,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,2007-11-16,36.7,19.3,193.0,3450.0,FEMALE

In [ ]:
# Padronizar os nomes das espécies
df['SPECIES'] = df['SPECIES'].str.split().str[0]
df['SPECIES'].value_counts()

SPECIES
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [ ]:
# Padronizar as categorias de sexo
df['SEX'] = df['SEX'].str.lower()
df['SEX'].value_counts()

SEX
male      168
female    165
Name: count, dtype: int64

In [ ]:
# Conversão de tipos qualitativos nominais
cols = df.columns.to_list()
cols_cat = cols[:4] + [cols[-1]]
for col in cols_cat:
    df[col] = df[col].astype('category')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   SPECIES         344 non-null    category
 1   REGION          344 non-null    category
 2   ISLAND          344 non-null    category
 3   DATE_EGG        344 non-null    category
 4   CULMEN_LENGTH   342 non-null    float64
 5   CULMEN_DEPTH    342 non-null    float64
 6   FLIPPER_LENGTH  342 non-null    float64
 7   BODY_MASS       342 non-null    float64
 8   SEX             333 non-null    category
dtypes: category(5), float64(4)
memory usage: 15.5 KB

In [ ]:
# Conversão para tipo quantitativos contínuos
cols_num = cols[4:7]
for col in cols_num:
    df[col] = df[col].astype('float')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   SPECIES         344 non-null    category
 1   REGION          344 non-null    category
 2   ISLAND          344 non-null    category
 3   DATE_EGG        344 non-null    category
 4   CULMEN_LENGTH   342 non-null    float64
 5   CULMEN_DEPTH    342 non-null    float64
 6   FLIPPER_LENGTH  342 non-null    float64
 7   BODY_MASS       342 non-null    float64
 8   SEX             333 non-null    category
dtypes: category(5), float64(4)
memory usage: 15.5 KB

In [ ]:
# Conversão para tipos quantitativos discretos
df['DATE_EGG'] = pd.to_datetime(df['DATE_EGG'], format='%Y-%m-%d')
df['YEAR'] = df['DATE_EGG'].dt.year
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   SPECIES         344 non-null    category
 1   ISLAND          344 non-null    category
 2   DATE_EGG        344 non-null    category
 3   CULMEN_LENGTH   342 non-null    float64
 4   CULMEN_DEPTH    342 non-null    float64
 5   FLIPPER_LENGTH  342 non-null    float64
 6   BODY_MASS       342 non-null    float64
 7   SEX             333 non-null    category
 8   YEAR            344 non-null    int32
dtypes: category(4), float64(4), int32(1)
memory usage: 16.4 KB

In [ ]:
# Removendo uma coluna
df = df.drop(columns='REGION')

df.head()

,SPECIES,ISLAND,DATE_EGG,CULMEN_LENGTH,CULMEN_DEPTH,FLIPPER_LENGTH,BODY_MASS,SEX,YEAR
0,Adelie,Torgersen,2007-11-11,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,2007-11-11,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,2007-11-16,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,2007-11-16,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,2007-11-16,36.7,19.3,193.0,3450.0,female,2007

In [ ]:
# Exportando o dado
df.to_csv('penguins.csv', index=False)